// Version history
// 0.2.0: streams added
// 0.2.1: callback-state added
// 0.2.2: block-on, close-read, is-read-closed added
// 0.3.0: start-writing/reading can fail, remove is-ready-to-write, remove read/write_ready_activate
// 0.3.1: register-unique
package symmetric:runtime@0.3.1;

world executor {
    export symmetric-executor;
}

world stream-impl {
    import symmetric-executor;
    export symmetric-stream;
}

world executor-import {
    import symmetric-executor;
}

world stream-import {
    import symmetric-stream;
}

world module {
    import symmetric-executor;
    import symmetric-stream;
}
