[package]
name = "test"
version = "0.1.0"
edition = "2021"

[dependencies]
#wit-bindgen-symmetric-rt = { path = "../../../../symmetric_executor/rust-client" }
wit-bindgen = { path = "../../../../symmetric_executor/bindgen", package = "mini-bindgen" }
symmetric_executor = { path = "../../../../symmetric_executor", features = ["trace"]}
symmetric_stream = { path = "../../../../symmetric_executor/symmetric_stream", features = ["trace"] }

[lib]
crate-type = ["cdylib"]
