// Generated by `wit-bindgen` 0.47.0. DO NOT EDIT!
// Options used:
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod symmetric {
    pub mod runtime {
        /// This interface will only work with symmetric ABI (shared everything),
        /// it can't be composed with the canonical ABI
        /// Asynchronous executor functionality for symmetric ABI
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod symmetric_executor {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            /// These pseudo-resources are just used to
            /// pass pointers to register
            /// Return value of an event callback
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum CallbackState {
                /// Call the function again
                Pending,
                /// The function has completed, all results are written, data is freed,
                /// calling the function again is not permitted as data became invalid!
                Ready,
            }
            impl ::core::fmt::Debug for CallbackState {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        CallbackState::Pending => {
                            f.debug_tuple("CallbackState::Pending").finish()
                        }
                        CallbackState::Ready => {
                            f.debug_tuple("CallbackState::Ready").finish()
                        }
                    }
                }
            }
            impl CallbackState {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> CallbackState {
                    if !cfg!(debug_assertions) {
                        return unsafe { ::core::mem::transmute(val) };
                    }
                    match val {
                        0 => CallbackState::Pending,
                        1 => CallbackState::Ready,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            /// This wraps a user provided function of type
            /// `fn (callback-data) -> callback-state`
            #[derive(Debug)]
            #[repr(transparent)]
            pub struct CallbackFunction {
                handle: _rt::Resource<CallbackFunction>,
            }
            impl CallbackFunction {
                #[doc(hidden)]
                pub unsafe fn from_handle(handle: usize) -> Self {
                    Self {
                        handle: unsafe { _rt::Resource::from_handle(handle) },
                    }
                }
                #[doc(hidden)]
                pub fn take_handle(&self) -> usize {
                    _rt::Resource::take_handle(&self.handle)
                }
                #[doc(hidden)]
                pub fn handle(&self) -> usize {
                    _rt::Resource::handle(&self.handle)
                }
            }
            unsafe impl _rt::WasmResource for CallbackFunction {
                #[inline]
                unsafe fn drop(_handle: usize) {
                    #[link(
                        wasm_import_module = "symmetric:runtime/symmetric-executor@0.3.0"
                    )]
                    unsafe extern "C" {
                        #[allow(non_snake_case)]
                        #[cfg_attr(
                            target_arch = "wasm32",
                            link_name = "[resource-drop]callback-function"
                        )]
                        fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5Bresource_dropX5Dcallback_function(
                            _: *mut u8,
                        );
                    }
                    unsafe {
                        symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5Bresource_dropX5Dcallback_function(
                            _handle as *mut u8,
                        )
                    };
                }
            }
            /// This wraps opaque user data, freed by the callback when
            /// it returns ready
            #[derive(Debug)]
            #[repr(transparent)]
            pub struct CallbackData {
                handle: _rt::Resource<CallbackData>,
            }
            impl CallbackData {
                #[doc(hidden)]
                pub unsafe fn from_handle(handle: usize) -> Self {
                    Self {
                        handle: unsafe { _rt::Resource::from_handle(handle) },
                    }
                }
                #[doc(hidden)]
                pub fn take_handle(&self) -> usize {
                    _rt::Resource::take_handle(&self.handle)
                }
                #[doc(hidden)]
                pub fn handle(&self) -> usize {
                    _rt::Resource::handle(&self.handle)
                }
            }
            unsafe impl _rt::WasmResource for CallbackData {
                #[inline]
                unsafe fn drop(_handle: usize) {
                    #[link(
                        wasm_import_module = "symmetric:runtime/symmetric-executor@0.3.0"
                    )]
                    unsafe extern "C" {
                        #[allow(non_snake_case)]
                        #[cfg_attr(
                            target_arch = "wasm32",
                            link_name = "[resource-drop]callback-data"
                        )]
                        fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5Bresource_dropX5Dcallback_data(
                            _: *mut u8,
                        );
                    }
                    unsafe {
                        symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5Bresource_dropX5Dcallback_data(
                            _handle as *mut u8,
                        )
                    };
                }
            }
            /// The receiving side of an event
            #[derive(Debug)]
            #[repr(transparent)]
            pub struct EventSubscription {
                handle: _rt::Resource<EventSubscription>,
            }
            impl EventSubscription {
                #[doc(hidden)]
                pub unsafe fn from_handle(handle: usize) -> Self {
                    Self {
                        handle: unsafe { _rt::Resource::from_handle(handle) },
                    }
                }
                #[doc(hidden)]
                pub fn take_handle(&self) -> usize {
                    _rt::Resource::take_handle(&self.handle)
                }
                #[doc(hidden)]
                pub fn handle(&self) -> usize {
                    _rt::Resource::handle(&self.handle)
                }
            }
            unsafe impl _rt::WasmResource for EventSubscription {
                #[inline]
                unsafe fn drop(_handle: usize) {
                    #[link(
                        wasm_import_module = "symmetric:runtime/symmetric-executor@0.3.0"
                    )]
                    unsafe extern "C" {
                        #[allow(non_snake_case)]
                        #[cfg_attr(
                            target_arch = "wasm32",
                            link_name = "[resource-drop]event-subscription"
                        )]
                        fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5Bresource_dropX5Devent_subscription(
                            _: *mut u8,
                        );
                    }
                    unsafe {
                        symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5Bresource_dropX5Devent_subscription(
                            _handle as *mut u8,
                        )
                    };
                }
            }
            /// A user controlled event
            #[derive(Debug)]
            #[repr(transparent)]
            pub struct EventGenerator {
                handle: _rt::Resource<EventGenerator>,
            }
            impl EventGenerator {
                #[doc(hidden)]
                pub unsafe fn from_handle(handle: usize) -> Self {
                    Self {
                        handle: unsafe { _rt::Resource::from_handle(handle) },
                    }
                }
                #[doc(hidden)]
                pub fn take_handle(&self) -> usize {
                    _rt::Resource::take_handle(&self.handle)
                }
                #[doc(hidden)]
                pub fn handle(&self) -> usize {
                    _rt::Resource::handle(&self.handle)
                }
            }
            unsafe impl _rt::WasmResource for EventGenerator {
                #[inline]
                unsafe fn drop(_handle: usize) {
                    #[link(
                        wasm_import_module = "symmetric:runtime/symmetric-executor@0.3.0"
                    )]
                    unsafe extern "C" {
                        #[allow(non_snake_case)]
                        #[cfg_attr(
                            target_arch = "wasm32",
                            link_name = "[resource-drop]event-generator"
                        )]
                        fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5Bresource_dropX5Devent_generator(
                            _: *mut u8,
                        );
                    }
                    unsafe {
                        symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5Bresource_dropX5Devent_generator(
                            _handle as *mut u8,
                        )
                    };
                }
            }
            /// Handle to cancel a callback registration
            #[derive(Debug)]
            #[repr(transparent)]
            pub struct CallbackRegistration {
                handle: _rt::Resource<CallbackRegistration>,
            }
            impl CallbackRegistration {
                #[doc(hidden)]
                pub unsafe fn from_handle(handle: usize) -> Self {
                    Self {
                        handle: unsafe { _rt::Resource::from_handle(handle) },
                    }
                }
                #[doc(hidden)]
                pub fn take_handle(&self) -> usize {
                    _rt::Resource::take_handle(&self.handle)
                }
                #[doc(hidden)]
                pub fn handle(&self) -> usize {
                    _rt::Resource::handle(&self.handle)
                }
            }
            unsafe impl _rt::WasmResource for CallbackRegistration {
                #[inline]
                unsafe fn drop(_handle: usize) {
                    #[link(
                        wasm_import_module = "symmetric:runtime/symmetric-executor@0.3.0"
                    )]
                    unsafe extern "C" {
                        #[allow(non_snake_case)]
                        #[cfg_attr(
                            target_arch = "wasm32",
                            link_name = "[resource-drop]callback-registration"
                        )]
                        fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5Bresource_dropX5Dcallback_registration(
                            _: *mut u8,
                        );
                    }
                    unsafe {
                        symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5Bresource_dropX5Dcallback_registration(
                            _handle as *mut u8,
                        )
                    };
                }
            }
            /// Return value of an async call, lowest bit encoding
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum CallStatus {
                /// For symmetric this means that processing has started, parameters should still remain valid until null,
                /// params-read = non-null, results-written,done = null
                Started,
                /// For symmetric: Retry the call (temporarily out of memory)
                NotStarted,
            }
            impl ::core::fmt::Debug for CallStatus {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        CallStatus::Started => {
                            f.debug_tuple("CallStatus::Started").finish()
                        }
                        CallStatus::NotStarted => {
                            f.debug_tuple("CallStatus::NotStarted").finish()
                        }
                    }
                }
            }
            impl CallStatus {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> CallStatus {
                    if !cfg!(debug_assertions) {
                        return unsafe { ::core::mem::transmute(val) };
                    }
                    match val {
                        0 => CallStatus::Started,
                        1 => CallStatus::NotStarted,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            impl EventSubscription {
                #[allow(unused_unsafe, clippy::all)]
                /// Whether the event is active (used by poll implementation)
                #[allow(async_fn_in_trait)]
                pub fn ready(&self) -> bool {
                    unsafe {
                        #[link(name = "symmetric_executor")]
                        #[link(
                            wasm_import_module = "symmetric:runtime/symmetric-executor@0.3.0"
                        )]
                        unsafe extern "C" {
                            #[allow(non_snake_case)]
                            #[cfg_attr(
                                target_arch = "wasm32",
                                link_name = "[method]event-subscription.ready"
                            )]
                            fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5BmethodX5Devent_subscriptionX2Eready(
                                _: *mut u8,
                            ) -> i32;
                        }
                        let ret = symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5BmethodX5Devent_subscriptionX2Eready(
                            (self).handle() as *mut u8,
                        );
                        _rt::bool_lift(ret as u8)
                    }
                }
            }
            impl EventSubscription {
                #[allow(unused_unsafe, clippy::all)]
                /// Create a timeout event
                #[allow(async_fn_in_trait)]
                pub fn from_timeout(nanoseconds: u64) -> EventSubscription {
                    unsafe {
                        #[link(name = "symmetric_executor")]
                        #[link(
                            wasm_import_module = "symmetric:runtime/symmetric-executor@0.3.0"
                        )]
                        unsafe extern "C" {
                            #[allow(non_snake_case)]
                            #[cfg_attr(
                                target_arch = "wasm32",
                                link_name = "[static]event-subscription.from-timeout"
                            )]
                            fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5BstaticX5Devent_subscriptionX2Efrom_timeout(
                                _: i64,
                            ) -> *mut u8;
                        }
                        let ret = symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5BstaticX5Devent_subscriptionX2Efrom_timeout(
                            _rt::as_i64(&nanoseconds),
                        );
                        EventSubscription::from_handle(ret as usize)
                    }
                }
            }
            impl EventSubscription {
                #[allow(unused_unsafe, clippy::all)]
                /// Duplicate the subscription (e.g. for repeated callback registering, same cost as subscribe)
                #[allow(async_fn_in_trait)]
                pub fn dup(&self) -> EventSubscription {
                    unsafe {
                        #[link(name = "symmetric_executor")]
                        #[link(
                            wasm_import_module = "symmetric:runtime/symmetric-executor@0.3.0"
                        )]
                        unsafe extern "C" {
                            #[allow(non_snake_case)]
                            #[cfg_attr(
                                target_arch = "wasm32",
                                link_name = "[method]event-subscription.dup"
                            )]
                            fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5BmethodX5Devent_subscriptionX2Edup(
                                _: *mut u8,
                            ) -> *mut u8;
                        }
                        let ret = symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5BmethodX5Devent_subscriptionX2Edup(
                            (self).handle() as *mut u8,
                        );
                        EventSubscription::from_handle(ret as usize)
                    }
                }
            }
            impl EventSubscription {
                #[allow(unused_unsafe, clippy::all)]
                /// Reset subscription to be inactive, only next trigger will ready it
                #[allow(async_fn_in_trait)]
                pub fn reset(&self) -> () {
                    unsafe {
                        #[link(name = "symmetric_executor")]
                        #[link(
                            wasm_import_module = "symmetric:runtime/symmetric-executor@0.3.0"
                        )]
                        unsafe extern "C" {
                            #[allow(non_snake_case)]
                            #[cfg_attr(
                                target_arch = "wasm32",
                                link_name = "[method]event-subscription.reset"
                            )]
                            fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5BmethodX5Devent_subscriptionX2Ereset(
                                _: *mut u8,
                            );
                        }
                        symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5BmethodX5Devent_subscriptionX2Ereset(
                            (self).handle() as *mut u8,
                        );
                    }
                }
            }
            impl EventGenerator {
                #[allow(unused_unsafe, clippy::all)]
                #[allow(async_fn_in_trait)]
                pub fn new() -> Self {
                    unsafe {
                        #[link(name = "symmetric_executor")]
                        #[link(
                            wasm_import_module = "symmetric:runtime/symmetric-executor@0.3.0"
                        )]
                        unsafe extern "C" {
                            #[allow(non_snake_case)]
                            #[cfg_attr(
                                target_arch = "wasm32",
                                link_name = "[constructor]event-generator"
                            )]
                            fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5BconstructorX5Devent_generator() -> *mut u8;
                        }
                        let ret = symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5BconstructorX5Devent_generator();
                        EventGenerator::from_handle(ret as usize)
                    }
                }
            }
            impl EventGenerator {
                #[allow(unused_unsafe, clippy::all)]
                /// Get the receiving side (to pass to other parts of the program)
                #[allow(async_fn_in_trait)]
                pub fn subscribe(&self) -> EventSubscription {
                    unsafe {
                        #[link(name = "symmetric_executor")]
                        #[link(
                            wasm_import_module = "symmetric:runtime/symmetric-executor@0.3.0"
                        )]
                        unsafe extern "C" {
                            #[allow(non_snake_case)]
                            #[cfg_attr(
                                target_arch = "wasm32",
                                link_name = "[method]event-generator.subscribe"
                            )]
                            fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5BmethodX5Devent_generatorX2Esubscribe(
                                _: *mut u8,
                            ) -> *mut u8;
                        }
                        let ret = symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5BmethodX5Devent_generatorX2Esubscribe(
                            (self).handle() as *mut u8,
                        );
                        EventSubscription::from_handle(ret as usize)
                    }
                }
            }
            impl EventGenerator {
                #[allow(unused_unsafe, clippy::all)]
                /// Trigger all subscribers
                #[allow(async_fn_in_trait)]
                pub fn activate(&self) -> () {
                    unsafe {
                        #[link(name = "symmetric_executor")]
                        #[link(
                            wasm_import_module = "symmetric:runtime/symmetric-executor@0.3.0"
                        )]
                        unsafe extern "C" {
                            #[allow(non_snake_case)]
                            #[cfg_attr(
                                target_arch = "wasm32",
                                link_name = "[method]event-generator.activate"
                            )]
                            fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5BmethodX5Devent_generatorX2Eactivate(
                                _: *mut u8,
                            );
                        }
                        symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5BmethodX5Devent_generatorX2Eactivate(
                            (self).handle() as *mut u8,
                        );
                    }
                }
            }
            impl CallbackRegistration {
                #[allow(unused_unsafe, clippy::all)]
                /// returns the data passed to the registration
                #[allow(async_fn_in_trait)]
                pub fn cancel(obj: CallbackRegistration) -> CallbackData {
                    unsafe {
                        #[link(name = "symmetric_executor")]
                        #[link(
                            wasm_import_module = "symmetric:runtime/symmetric-executor@0.3.0"
                        )]
                        unsafe extern "C" {
                            #[allow(non_snake_case)]
                            #[cfg_attr(
                                target_arch = "wasm32",
                                link_name = "[static]callback-registration.cancel"
                            )]
                            fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5BstaticX5Dcallback_registrationX2Ecancel(
                                _: *mut u8,
                            ) -> *mut u8;
                        }
                        let ret = symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5BstaticX5Dcallback_registrationX2Ecancel(
                            (&obj).take_handle() as *mut u8,
                        );
                        CallbackData::from_handle(ret as usize)
                    }
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Wait until all registered events have completed
            #[allow(async_fn_in_trait)]
            pub fn run() -> () {
                unsafe {
                    #[link(name = "symmetric_executor")]
                    #[link(
                        wasm_import_module = "symmetric:runtime/symmetric-executor@0.3.0"
                    )]
                    unsafe extern "C" {
                        #[allow(non_snake_case)]
                        #[cfg_attr(target_arch = "wasm32", link_name = "run")]
                        fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00run();
                    }
                    symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00run();
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Register a callback for an event
            #[allow(async_fn_in_trait)]
            pub fn register(
                trigger: EventSubscription,
                callback: CallbackFunction,
                data: CallbackData,
            ) -> CallbackRegistration {
                unsafe {
                    #[link(name = "symmetric_executor")]
                    #[link(
                        wasm_import_module = "symmetric:runtime/symmetric-executor@0.3.0"
                    )]
                    unsafe extern "C" {
                        #[allow(non_snake_case)]
                        #[cfg_attr(target_arch = "wasm32", link_name = "register")]
                        fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00register(
                            _: *mut u8,
                            _: *mut u8,
                            _: *mut u8,
                        ) -> *mut u8;
                    }
                    let ret = symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00register(
                        (&trigger).take_handle() as *mut u8,
                        (&callback).take_handle() as *mut u8,
                        (&data).take_handle() as *mut u8,
                    );
                    CallbackRegistration::from_handle(ret as usize)
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Wait for a specific event
            #[allow(async_fn_in_trait)]
            pub fn block_on(trigger: EventSubscription) -> () {
                unsafe {
                    #[link(name = "symmetric_executor")]
                    #[link(
                        wasm_import_module = "symmetric:runtime/symmetric-executor@0.3.0"
                    )]
                    unsafe extern "C" {
                        #[allow(non_snake_case)]
                        #[cfg_attr(target_arch = "wasm32", link_name = "block-on")]
                        fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00block_on(
                            _: *mut u8,
                        );
                    }
                    symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00block_on(
                        (&trigger).take_handle() as *mut u8,
                    );
                }
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    use core::fmt;
    use core::marker;
    use core::sync::atomic::{AtomicUsize, Ordering::Relaxed};
    /// A type which represents a component model resource, either imported or
    /// exported into this component.
    ///
    /// This is a low-level wrapper which handles the lifetime of the resource
    /// (namely this has a destructor). The `T` provided defines the component model
    /// intrinsics that this wrapper uses.
    ///
    /// One of the chief purposes of this type is to provide `Deref` implementations
    /// to access the underlying data when it is owned.
    ///
    /// This type is primarily used in generated code for exported and imported
    /// resources.
    #[repr(transparent)]
    pub struct Resource<T: WasmResource> {
        handle: AtomicUsize,
        _marker: marker::PhantomData<T>,
    }
    /// A trait which all wasm resources implement, namely providing the ability to
    /// drop a resource.
    ///
    /// This generally is implemented by generated code, not user-facing code.
    #[allow(clippy::missing_safety_doc)]
    pub unsafe trait WasmResource {
        /// Invokes the `[resource-drop]...` intrinsic.
        unsafe fn drop(handle: usize);
    }
    impl<T: WasmResource> Resource<T> {
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: usize) -> Self {
            debug_assert!(handle != 0 && handle != 0);
            Self {
                handle: AtomicUsize::new(handle),
                _marker: marker::PhantomData,
            }
        }
        /// Takes ownership of the handle owned by `resource`.
        ///
        /// Note that this ideally would be `into_handle` taking `Resource<T>` by
        /// ownership. The code generator does not enable that in all situations,
        /// unfortunately, so this is provided instead.
        ///
        /// Also note that `take_handle` is in theory only ever called on values
        /// owned by a generated function. For example a generated function might
        /// take `Resource<T>` as an argument but then call `take_handle` on a
        /// reference to that argument. In that sense the dynamic nature of
        /// `take_handle` should only be exposed internally to generated code, not
        /// to user code.
        #[doc(hidden)]
        pub fn take_handle(resource: &Resource<T>) -> usize {
            resource.handle.swap(0, Relaxed)
        }
        #[doc(hidden)]
        pub fn handle(resource: &Resource<T>) -> usize {
            resource.handle.load(Relaxed)
        }
    }
    impl<T: WasmResource> fmt::Debug for Resource<T> {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            f.debug_struct("Resource").field("handle", &self.handle).finish()
        }
    }
    impl<T: WasmResource> Drop for Resource<T> {
        fn drop(&mut self) {
            unsafe {
                match self.handle.load(Relaxed) {
                    0 => {}
                    other => T::drop(other),
                }
            }
        }
    }
    pub unsafe fn bool_lift(val: u8) -> bool {
        if cfg!(debug_assertions) {
            match val {
                0 => false,
                1 => true,
                _ => panic!("invalid bool discriminant"),
            }
        } else {
            val != 0
        }
    }
    pub fn as_i64<T: AsI64>(t: T) -> i64 {
        t.as_i64()
    }
    pub trait AsI64 {
        fn as_i64(self) -> i64;
    }
    impl<'a, T: Copy + AsI64> AsI64 for &'a T {
        fn as_i64(self) -> i64 {
            (*self).as_i64()
        }
    }
    impl AsI64 for i64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    impl AsI64 for u64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
}
#[rustfmt::skip]
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.47.0:symmetric:runtime@0.3.0:executor-import:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 914] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x8c\x06\x01A\x02\x01\
A\x02\x01B&\x01m\x02\x07pending\x05ready\x04\0\x0ecallback-state\x03\0\0\x04\0\x11\
callback-function\x03\x01\x04\0\x0dcallback-data\x03\x01\x04\0\x12event-subscrip\
tion\x03\x01\x04\0\x0fevent-generator\x03\x01\x04\0\x15callback-registration\x03\
\x01\x01m\x02\x07started\x0bnot-started\x04\0\x0bcall-status\x03\0\x07\x01h\x04\x01\
@\x01\x04self\x09\0\x7f\x04\0\x20[method]event-subscription.ready\x01\x0a\x01i\x04\
\x01@\x01\x0bnanosecondsw\0\x0b\x04\0'[static]event-subscription.from-timeout\x01\
\x0c\x01@\x01\x04self\x09\0\x0b\x04\0\x1e[method]event-subscription.dup\x01\x0d\x01\
@\x01\x04self\x09\x01\0\x04\0\x20[method]event-subscription.reset\x01\x0e\x01i\x05\
\x01@\0\0\x0f\x04\0\x1c[constructor]event-generator\x01\x10\x01h\x05\x01@\x01\x04\
self\x11\0\x0b\x04\0![method]event-generator.subscribe\x01\x12\x01@\x01\x04self\x11\
\x01\0\x04\0\x20[method]event-generator.activate\x01\x13\x01i\x06\x01i\x03\x01@\x01\
\x03obj\x14\0\x15\x04\0$[static]callback-registration.cancel\x01\x16\x01@\0\x01\0\
\x04\0\x03run\x01\x17\x01i\x02\x01@\x03\x07trigger\x0b\x08callback\x18\x04data\x15\
\0\x14\x04\0\x08register\x01\x19\x01@\x01\x07trigger\x0b\x01\0\x04\0\x08block-on\
\x01\x1a\x03\0*symmetric:runtime/symmetric-executor@0.3.0\x05\0\x04\0'symmetric:\
runtime/executor-import@0.3.0\x04\0\x0b\x15\x01\0\x0fexecutor-import\x03\0\0\0G\x09\
producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.240.0\x10wit-bindgen-rus\
t\x060.47.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen::rt::maybe_link_cabi_realloc();
}
