// Generated by `wit-bindgen` 0.47.0. DO NOT EDIT!
// Options used:
//   * with "symmetric:runtime/symmetric-executor@0.3.0" = "crate::symmetric_executor"
#[allow(unfulfilled_lint_expectations, unused_imports)]
use crate::symmetric_executor as __with_name0;
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod symmetric {
    pub mod runtime {
        /// language neutral stream implementation
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod symmetric_stream {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            pub type EventSubscription = super::super::super::__with_name0::EventSubscription;
            #[derive(Debug)]
            #[repr(transparent)]
            pub struct Address {
                handle: _rt::Resource<Address>,
            }
            impl Address {
                #[doc(hidden)]
                pub unsafe fn from_handle(handle: usize) -> Self {
                    Self {
                        handle: unsafe { _rt::Resource::from_handle(handle) },
                    }
                }
                #[doc(hidden)]
                pub fn take_handle(&self) -> usize {
                    _rt::Resource::take_handle(&self.handle)
                }
                #[doc(hidden)]
                pub fn handle(&self) -> usize {
                    _rt::Resource::handle(&self.handle)
                }
            }
            unsafe impl _rt::WasmResource for Address {
                #[inline]
                unsafe fn drop(_handle: usize) {
                    #[link(
                        wasm_import_module = "symmetric:runtime/symmetric-stream@0.3.0"
                    )]
                    unsafe extern "C" {
                        #[allow(non_snake_case)]
                        #[cfg_attr(
                            target_arch = "wasm32",
                            link_name = "[resource-drop]address"
                        )]
                        fn symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E0X00X5Bresource_dropX5Daddress(
                            _: *mut u8,
                        );
                    }
                    unsafe {
                        symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E0X00X5Bresource_dropX5Daddress(
                            _handle as *mut u8,
                        )
                    };
                }
            }
            /// special zero allocation/copy data type (caller provided buffer)
            #[derive(Debug)]
            #[repr(transparent)]
            pub struct Buffer {
                handle: _rt::Resource<Buffer>,
            }
            impl Buffer {
                #[doc(hidden)]
                pub unsafe fn from_handle(handle: usize) -> Self {
                    Self {
                        handle: unsafe { _rt::Resource::from_handle(handle) },
                    }
                }
                #[doc(hidden)]
                pub fn take_handle(&self) -> usize {
                    _rt::Resource::take_handle(&self.handle)
                }
                #[doc(hidden)]
                pub fn handle(&self) -> usize {
                    _rt::Resource::handle(&self.handle)
                }
            }
            unsafe impl _rt::WasmResource for Buffer {
                #[inline]
                unsafe fn drop(_handle: usize) {
                    #[link(
                        wasm_import_module = "symmetric:runtime/symmetric-stream@0.3.0"
                    )]
                    unsafe extern "C" {
                        #[allow(non_snake_case)]
                        #[cfg_attr(
                            target_arch = "wasm32",
                            link_name = "[resource-drop]buffer"
                        )]
                        fn symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E0X00X5Bresource_dropX5Dbuffer(
                            _: *mut u8,
                        );
                    }
                    unsafe {
                        symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E0X00X5Bresource_dropX5Dbuffer(
                            _handle as *mut u8,
                        )
                    };
                }
            }
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum StreamState {
                Eof,
                Pending,
            }
            impl StreamState {
                pub fn name(&self) -> &'static str {
                    match self {
                        StreamState::Eof => "eof",
                        StreamState::Pending => "pending",
                    }
                }
                pub fn message(&self) -> &'static str {
                    match self {
                        StreamState::Eof => "",
                        StreamState::Pending => "",
                    }
                }
            }
            impl ::core::fmt::Debug for StreamState {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("StreamState")
                        .field("code", &(*self as i32))
                        .field("name", &self.name())
                        .field("message", &self.message())
                        .finish()
                }
            }
            impl ::core::fmt::Display for StreamState {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    write!(f, "{} (error {})", self.name(), * self as i32)
                }
            }
            impl ::core::error::Error for StreamState {}
            impl StreamState {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> StreamState {
                    if !cfg!(debug_assertions) {
                        return unsafe { ::core::mem::transmute(val) };
                    }
                    match val {
                        0 => StreamState::Eof,
                        1 => StreamState::Pending,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            #[derive(Debug)]
            #[repr(transparent)]
            pub struct StreamObj {
                handle: _rt::Resource<StreamObj>,
            }
            impl StreamObj {
                #[doc(hidden)]
                pub unsafe fn from_handle(handle: usize) -> Self {
                    Self {
                        handle: unsafe { _rt::Resource::from_handle(handle) },
                    }
                }
                #[doc(hidden)]
                pub fn take_handle(&self) -> usize {
                    _rt::Resource::take_handle(&self.handle)
                }
                #[doc(hidden)]
                pub fn handle(&self) -> usize {
                    _rt::Resource::handle(&self.handle)
                }
            }
            unsafe impl _rt::WasmResource for StreamObj {
                #[inline]
                unsafe fn drop(_handle: usize) {
                    #[link(
                        wasm_import_module = "symmetric:runtime/symmetric-stream@0.3.0"
                    )]
                    unsafe extern "C" {
                        #[allow(non_snake_case)]
                        #[cfg_attr(
                            target_arch = "wasm32",
                            link_name = "[resource-drop]stream-obj"
                        )]
                        fn symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E0X00X5Bresource_dropX5Dstream_obj(
                            _: *mut u8,
                        );
                    }
                    unsafe {
                        symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E0X00X5Bresource_dropX5Dstream_obj(
                            _handle as *mut u8,
                        )
                    };
                }
            }
            impl Buffer {
                #[allow(unused_unsafe, clippy::all)]
                #[allow(async_fn_in_trait)]
                pub fn new(addr: Address, capacity: u64) -> Self {
                    unsafe {
                        #[link(name = "symmetric_stream")]
                        #[link(
                            wasm_import_module = "symmetric:runtime/symmetric-stream@0.3.0"
                        )]
                        unsafe extern "C" {
                            #[allow(non_snake_case)]
                            #[cfg_attr(
                                target_arch = "wasm32",
                                link_name = "[constructor]buffer"
                            )]
                            fn symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E0X00X5BconstructorX5Dbuffer(
                                _: *mut u8,
                                _: i64,
                            ) -> *mut u8;
                        }
                        let ret = symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E0X00X5BconstructorX5Dbuffer(
                            (&addr).take_handle() as *mut u8,
                            _rt::as_i64(&capacity),
                        );
                        Buffer::from_handle(ret as usize)
                    }
                }
            }
            impl Buffer {
                #[allow(unused_unsafe, clippy::all)]
                #[allow(async_fn_in_trait)]
                pub fn get_address(&self) -> Address {
                    unsafe {
                        #[link(name = "symmetric_stream")]
                        #[link(
                            wasm_import_module = "symmetric:runtime/symmetric-stream@0.3.0"
                        )]
                        unsafe extern "C" {
                            #[allow(non_snake_case)]
                            #[cfg_attr(
                                target_arch = "wasm32",
                                link_name = "[method]buffer.get-address"
                            )]
                            fn symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E0X00X5BmethodX5DbufferX2Eget_address(
                                _: *mut u8,
                            ) -> *mut u8;
                        }
                        let ret = symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E0X00X5BmethodX5DbufferX2Eget_address(
                            (self).handle() as *mut u8,
                        );
                        Address::from_handle(ret as usize)
                    }
                }
            }
            impl Buffer {
                #[allow(unused_unsafe, clippy::all)]
                #[allow(async_fn_in_trait)]
                pub fn get_size(&self) -> u64 {
                    unsafe {
                        #[link(name = "symmetric_stream")]
                        #[link(
                            wasm_import_module = "symmetric:runtime/symmetric-stream@0.3.0"
                        )]
                        unsafe extern "C" {
                            #[allow(non_snake_case)]
                            #[cfg_attr(
                                target_arch = "wasm32",
                                link_name = "[method]buffer.get-size"
                            )]
                            fn symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E0X00X5BmethodX5DbufferX2Eget_size(
                                _: *mut u8,
                            ) -> i64;
                        }
                        let ret = symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E0X00X5BmethodX5DbufferX2Eget_size(
                            (self).handle() as *mut u8,
                        );
                        ret as u64
                    }
                }
            }
            impl Buffer {
                #[allow(unused_unsafe, clippy::all)]
                #[allow(async_fn_in_trait)]
                pub fn set_size(&self, size: u64) -> () {
                    unsafe {
                        #[link(name = "symmetric_stream")]
                        #[link(
                            wasm_import_module = "symmetric:runtime/symmetric-stream@0.3.0"
                        )]
                        unsafe extern "C" {
                            #[allow(non_snake_case)]
                            #[cfg_attr(
                                target_arch = "wasm32",
                                link_name = "[method]buffer.set-size"
                            )]
                            fn symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E0X00X5BmethodX5DbufferX2Eset_size(
                                _: *mut u8,
                                _: i64,
                            );
                        }
                        symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E0X00X5BmethodX5DbufferX2Eset_size(
                            (self).handle() as *mut u8,
                            _rt::as_i64(&size),
                        );
                    }
                }
            }
            impl Buffer {
                #[allow(unused_unsafe, clippy::all)]
                #[allow(async_fn_in_trait)]
                pub fn capacity(&self) -> u64 {
                    unsafe {
                        #[link(name = "symmetric_stream")]
                        #[link(
                            wasm_import_module = "symmetric:runtime/symmetric-stream@0.3.0"
                        )]
                        unsafe extern "C" {
                            #[allow(non_snake_case)]
                            #[cfg_attr(
                                target_arch = "wasm32",
                                link_name = "[method]buffer.capacity"
                            )]
                            fn symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E0X00X5BmethodX5DbufferX2Ecapacity(
                                _: *mut u8,
                            ) -> i64;
                        }
                        let ret = symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E0X00X5BmethodX5DbufferX2Ecapacity(
                            (self).handle() as *mut u8,
                        );
                        ret as u64
                    }
                }
            }
            impl StreamObj {
                #[allow(unused_unsafe, clippy::all)]
                #[allow(async_fn_in_trait)]
                pub fn new() -> Self {
                    unsafe {
                        #[link(name = "symmetric_stream")]
                        #[link(
                            wasm_import_module = "symmetric:runtime/symmetric-stream@0.3.0"
                        )]
                        unsafe extern "C" {
                            #[allow(non_snake_case)]
                            #[cfg_attr(
                                target_arch = "wasm32",
                                link_name = "[constructor]stream-obj"
                            )]
                            fn symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E0X00X5BconstructorX5Dstream_obj() -> *mut u8;
                        }
                        let ret = symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E0X00X5BconstructorX5Dstream_obj();
                        StreamObj::from_handle(ret as usize)
                    }
                }
            }
            impl StreamObj {
                #[allow(unused_unsafe, clippy::all)]
                /// create a new instance e.g. for reading or tasks
                /// (Assumption: This is never used to duplicate the writing side)
                #[allow(async_fn_in_trait)]
                pub fn clone(&self, writing: bool) -> StreamObj {
                    unsafe {
                        #[link(name = "symmetric_stream")]
                        #[link(
                            wasm_import_module = "symmetric:runtime/symmetric-stream@0.3.0"
                        )]
                        unsafe extern "C" {
                            #[allow(non_snake_case)]
                            #[cfg_attr(
                                target_arch = "wasm32",
                                link_name = "[method]stream-obj.clone"
                            )]
                            fn symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E0X00X5BmethodX5Dstream_objX2Eclone(
                                _: *mut u8,
                                _: i32,
                            ) -> *mut u8;
                        }
                        let ret = symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E0X00X5BmethodX5Dstream_objX2Eclone(
                            (self).handle() as *mut u8,
                            match &writing {
                                true => 1,
                                false => 0,
                            },
                        );
                        StreamObj::from_handle(ret as usize)
                    }
                }
            }
            impl StreamObj {
                #[allow(unused_unsafe, clippy::all)]
                /// reading (in roughly chronological order)
                /// indicates EOF
                #[allow(async_fn_in_trait)]
                pub fn is_write_closed(&self) -> bool {
                    unsafe {
                        #[link(name = "symmetric_stream")]
                        #[link(
                            wasm_import_module = "symmetric:runtime/symmetric-stream@0.3.0"
                        )]
                        unsafe extern "C" {
                            #[allow(non_snake_case)]
                            #[cfg_attr(
                                target_arch = "wasm32",
                                link_name = "[method]stream-obj.is-write-closed"
                            )]
                            fn symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E0X00X5BmethodX5Dstream_objX2Eis_write_closed(
                                _: *mut u8,
                            ) -> i32;
                        }
                        let ret = symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E0X00X5BmethodX5Dstream_objX2Eis_write_closed(
                            (self).handle() as *mut u8,
                        );
                        _rt::bool_lift(ret as u8)
                    }
                }
            }
            impl StreamObj {
                #[allow(unused_unsafe, clippy::all)]
                #[allow(async_fn_in_trait)]
                pub fn start_reading(&self, buffer: Buffer) -> Result<(), Buffer> {
                    unsafe {
                        #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                        #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                        struct RetArea(
                            [::core::mem::MaybeUninit<
                                u8,
                            >; 2 * ::core::mem::size_of::<*const u8>()],
                        );
                        let mut ret_area = RetArea(
                            [::core::mem::MaybeUninit::uninit(); 2
                                * ::core::mem::size_of::<*const u8>()],
                        );
                        let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                        #[link(name = "symmetric_stream")]
                        #[link(
                            wasm_import_module = "symmetric:runtime/symmetric-stream@0.3.0"
                        )]
                        unsafe extern "C" {
                            #[allow(non_snake_case)]
                            #[cfg_attr(
                                target_arch = "wasm32",
                                link_name = "[method]stream-obj.start-reading"
                            )]
                            fn symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E0X00X5BmethodX5Dstream_objX2Estart_reading(
                                _: *mut u8,
                                _: *mut u8,
                                _: *mut u8,
                            );
                        }
                        symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E0X00X5BmethodX5Dstream_objX2Estart_reading(
                            (self).handle() as *mut u8,
                            (&buffer).take_handle() as *mut u8,
                            ptr0,
                        );
                        let l1 = i32::from(*ptr0.add(0).cast::<u8>());
                        match l1 {
                            0 => {
                                let e = ();
                                Ok(e)
                            }
                            1 => {
                                let e = {
                                    let l2 = *ptr0
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    Buffer::from_handle(l2 as usize)
                                };
                                Err(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        }
                    }
                }
            }
            impl StreamObj {
                #[allow(unused_unsafe, clippy::all)]
                #[allow(async_fn_in_trait)]
                pub fn read_ready_subscribe(&self) -> EventSubscription {
                    unsafe {
                        #[link(name = "symmetric_stream")]
                        #[link(
                            wasm_import_module = "symmetric:runtime/symmetric-stream@0.3.0"
                        )]
                        unsafe extern "C" {
                            #[allow(non_snake_case)]
                            #[cfg_attr(
                                target_arch = "wasm32",
                                link_name = "[method]stream-obj.read-ready-subscribe"
                            )]
                            fn symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E0X00X5BmethodX5Dstream_objX2Eread_ready_subscribe(
                                _: *mut u8,
                            ) -> *mut u8;
                        }
                        let ret = symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E0X00X5BmethodX5Dstream_objX2Eread_ready_subscribe(
                            (self).handle() as *mut u8,
                        );
                        super::super::super::__with_name0::EventSubscription::from_handle(
                            ret as usize,
                        )
                    }
                }
            }
            impl StreamObj {
                #[allow(unused_unsafe, clippy::all)]
                /// close the reading side, returning any in-flight buffer(s)
                #[allow(async_fn_in_trait)]
                pub fn close_read(&self) -> _rt::Vec<Buffer> {
                    unsafe {
                        #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                        #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                        struct RetArea(
                            [::core::mem::MaybeUninit<
                                u8,
                            >; 2 * ::core::mem::size_of::<*const u8>()],
                        );
                        let mut ret_area = RetArea(
                            [::core::mem::MaybeUninit::uninit(); 2
                                * ::core::mem::size_of::<*const u8>()],
                        );
                        let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                        #[link(name = "symmetric_stream")]
                        #[link(
                            wasm_import_module = "symmetric:runtime/symmetric-stream@0.3.0"
                        )]
                        unsafe extern "C" {
                            #[allow(non_snake_case)]
                            #[cfg_attr(
                                target_arch = "wasm32",
                                link_name = "[method]stream-obj.close-read"
                            )]
                            fn symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E0X00X5BmethodX5Dstream_objX2Eclose_read(
                                _: *mut u8,
                                _: *mut u8,
                            );
                        }
                        symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E0X00X5BmethodX5Dstream_objX2Eclose_read(
                            (self).handle() as *mut u8,
                            ptr0,
                        );
                        let l1 = *ptr0.add(0).cast::<*mut u8>();
                        let l2 = *ptr0
                            .add(::core::mem::size_of::<*const u8>())
                            .cast::<usize>();
                        let base4 = l1;
                        let len4 = l2;
                        let mut result4 = _rt::Vec::with_capacity(len4);
                        for i in 0..len4 {
                            let base = base4
                                .add(i * ::core::mem::size_of::<*const u8>());
                            let e4 = {
                                let l3 = *base.add(0).cast::<*mut u8>();
                                Buffer::from_handle(l3 as usize)
                            };
                            result4.push(e4);
                        }
                        _rt::cabi_dealloc(
                            base4,
                            len4 * ::core::mem::size_of::<*const u8>(),
                            ::core::mem::size_of::<*const u8>(),
                        );
                        result4
                    }
                }
            }
            impl StreamObj {
                #[allow(unused_unsafe, clippy::all)]
                #[allow(async_fn_in_trait)]
                pub fn read_result(&self) -> Result<Buffer, StreamState> {
                    unsafe {
                        #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                        #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                        struct RetArea(
                            [::core::mem::MaybeUninit<
                                u8,
                            >; 2 * ::core::mem::size_of::<*const u8>()],
                        );
                        let mut ret_area = RetArea(
                            [::core::mem::MaybeUninit::uninit(); 2
                                * ::core::mem::size_of::<*const u8>()],
                        );
                        let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                        #[link(name = "symmetric_stream")]
                        #[link(
                            wasm_import_module = "symmetric:runtime/symmetric-stream@0.3.0"
                        )]
                        unsafe extern "C" {
                            #[allow(non_snake_case)]
                            #[cfg_attr(
                                target_arch = "wasm32",
                                link_name = "[method]stream-obj.read-result"
                            )]
                            fn symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E0X00X5BmethodX5Dstream_objX2Eread_result(
                                _: *mut u8,
                                _: *mut u8,
                            );
                        }
                        symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E0X00X5BmethodX5Dstream_objX2Eread_result(
                            (self).handle() as *mut u8,
                            ptr0,
                        );
                        let l1 = i32::from(*ptr0.add(0).cast::<u8>());
                        match l1 {
                            0 => {
                                let e = {
                                    let l2 = *ptr0
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    Buffer::from_handle(l2 as usize)
                                };
                                Ok(e)
                            }
                            1 => {
                                let e = {
                                    let l3 = i32::from(
                                        *ptr0.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                                    );
                                    StreamState::_lift(l3 as u8)
                                };
                                Err(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        }
                    }
                }
            }
            impl StreamObj {
                #[allow(unused_unsafe, clippy::all)]
                /// writing
                #[allow(async_fn_in_trait)]
                pub fn is_read_closed(&self) -> bool {
                    unsafe {
                        #[link(name = "symmetric_stream")]
                        #[link(
                            wasm_import_module = "symmetric:runtime/symmetric-stream@0.3.0"
                        )]
                        unsafe extern "C" {
                            #[allow(non_snake_case)]
                            #[cfg_attr(
                                target_arch = "wasm32",
                                link_name = "[method]stream-obj.is-read-closed"
                            )]
                            fn symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E0X00X5BmethodX5Dstream_objX2Eis_read_closed(
                                _: *mut u8,
                            ) -> i32;
                        }
                        let ret = symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E0X00X5BmethodX5Dstream_objX2Eis_read_closed(
                            (self).handle() as *mut u8,
                        );
                        _rt::bool_lift(ret as u8)
                    }
                }
            }
            impl StreamObj {
                #[allow(unused_unsafe, clippy::all)]
                #[allow(async_fn_in_trait)]
                pub fn start_writing(&self) -> Result<Buffer, StreamState> {
                    unsafe {
                        #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                        #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                        struct RetArea(
                            [::core::mem::MaybeUninit<
                                u8,
                            >; 2 * ::core::mem::size_of::<*const u8>()],
                        );
                        let mut ret_area = RetArea(
                            [::core::mem::MaybeUninit::uninit(); 2
                                * ::core::mem::size_of::<*const u8>()],
                        );
                        let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                        #[link(name = "symmetric_stream")]
                        #[link(
                            wasm_import_module = "symmetric:runtime/symmetric-stream@0.3.0"
                        )]
                        unsafe extern "C" {
                            #[allow(non_snake_case)]
                            #[cfg_attr(
                                target_arch = "wasm32",
                                link_name = "[method]stream-obj.start-writing"
                            )]
                            fn symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E0X00X5BmethodX5Dstream_objX2Estart_writing(
                                _: *mut u8,
                                _: *mut u8,
                            );
                        }
                        symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E0X00X5BmethodX5Dstream_objX2Estart_writing(
                            (self).handle() as *mut u8,
                            ptr0,
                        );
                        let l1 = i32::from(*ptr0.add(0).cast::<u8>());
                        match l1 {
                            0 => {
                                let e = {
                                    let l2 = *ptr0
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    Buffer::from_handle(l2 as usize)
                                };
                                Ok(e)
                            }
                            1 => {
                                let e = {
                                    let l3 = i32::from(
                                        *ptr0.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                                    );
                                    StreamState::_lift(l3 as u8)
                                };
                                Err(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        }
                    }
                }
            }
            impl StreamObj {
                #[allow(unused_unsafe, clippy::all)]
                #[allow(async_fn_in_trait)]
                pub fn write_ready_subscribe(&self) -> EventSubscription {
                    unsafe {
                        #[link(name = "symmetric_stream")]
                        #[link(
                            wasm_import_module = "symmetric:runtime/symmetric-stream@0.3.0"
                        )]
                        unsafe extern "C" {
                            #[allow(non_snake_case)]
                            #[cfg_attr(
                                target_arch = "wasm32",
                                link_name = "[method]stream-obj.write-ready-subscribe"
                            )]
                            fn symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E0X00X5BmethodX5Dstream_objX2Ewrite_ready_subscribe(
                                _: *mut u8,
                            ) -> *mut u8;
                        }
                        let ret = symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E0X00X5BmethodX5Dstream_objX2Ewrite_ready_subscribe(
                            (self).handle() as *mut u8,
                        );
                        super::super::super::__with_name0::EventSubscription::from_handle(
                            ret as usize,
                        )
                    }
                }
            }
            impl StreamObj {
                #[allow(unused_unsafe, clippy::all)]
                #[allow(async_fn_in_trait)]
                pub fn finish_writing(&self, buffer: Buffer) -> Result<(), Buffer> {
                    unsafe {
                        #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                        #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                        struct RetArea(
                            [::core::mem::MaybeUninit<
                                u8,
                            >; 2 * ::core::mem::size_of::<*const u8>()],
                        );
                        let mut ret_area = RetArea(
                            [::core::mem::MaybeUninit::uninit(); 2
                                * ::core::mem::size_of::<*const u8>()],
                        );
                        let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                        #[link(name = "symmetric_stream")]
                        #[link(
                            wasm_import_module = "symmetric:runtime/symmetric-stream@0.3.0"
                        )]
                        unsafe extern "C" {
                            #[allow(non_snake_case)]
                            #[cfg_attr(
                                target_arch = "wasm32",
                                link_name = "[method]stream-obj.finish-writing"
                            )]
                            fn symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E0X00X5BmethodX5Dstream_objX2Efinish_writing(
                                _: *mut u8,
                                _: *mut u8,
                                _: *mut u8,
                            );
                        }
                        symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E0X00X5BmethodX5Dstream_objX2Efinish_writing(
                            (self).handle() as *mut u8,
                            (&buffer).take_handle() as *mut u8,
                            ptr0,
                        );
                        let l1 = i32::from(*ptr0.add(0).cast::<u8>());
                        match l1 {
                            0 => {
                                let e = ();
                                Ok(e)
                            }
                            1 => {
                                let e = {
                                    let l2 = *ptr0
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    Buffer::from_handle(l2 as usize)
                                };
                                Err(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        }
                    }
                }
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    use core::fmt;
    use core::marker;
    use core::sync::atomic::{AtomicUsize, Ordering::Relaxed};
    /// A type which represents a component model resource, either imported or
    /// exported into this component.
    ///
    /// This is a low-level wrapper which handles the lifetime of the resource
    /// (namely this has a destructor). The `T` provided defines the component model
    /// intrinsics that this wrapper uses.
    ///
    /// One of the chief purposes of this type is to provide `Deref` implementations
    /// to access the underlying data when it is owned.
    ///
    /// This type is primarily used in generated code for exported and imported
    /// resources.
    #[repr(transparent)]
    pub struct Resource<T: WasmResource> {
        handle: AtomicUsize,
        _marker: marker::PhantomData<T>,
    }
    /// A trait which all wasm resources implement, namely providing the ability to
    /// drop a resource.
    ///
    /// This generally is implemented by generated code, not user-facing code.
    #[allow(clippy::missing_safety_doc)]
    pub unsafe trait WasmResource {
        /// Invokes the `[resource-drop]...` intrinsic.
        unsafe fn drop(handle: usize);
    }
    impl<T: WasmResource> Resource<T> {
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: usize) -> Self {
            debug_assert!(handle != 0 && handle != 0);
            Self {
                handle: AtomicUsize::new(handle),
                _marker: marker::PhantomData,
            }
        }
        /// Takes ownership of the handle owned by `resource`.
        ///
        /// Note that this ideally would be `into_handle` taking `Resource<T>` by
        /// ownership. The code generator does not enable that in all situations,
        /// unfortunately, so this is provided instead.
        ///
        /// Also note that `take_handle` is in theory only ever called on values
        /// owned by a generated function. For example a generated function might
        /// take `Resource<T>` as an argument but then call `take_handle` on a
        /// reference to that argument. In that sense the dynamic nature of
        /// `take_handle` should only be exposed internally to generated code, not
        /// to user code.
        #[doc(hidden)]
        pub fn take_handle(resource: &Resource<T>) -> usize {
            resource.handle.swap(0, Relaxed)
        }
        #[doc(hidden)]
        pub fn handle(resource: &Resource<T>) -> usize {
            resource.handle.load(Relaxed)
        }
    }
    impl<T: WasmResource> fmt::Debug for Resource<T> {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            f.debug_struct("Resource").field("handle", &self.handle).finish()
        }
    }
    impl<T: WasmResource> Drop for Resource<T> {
        fn drop(&mut self) {
            unsafe {
                match self.handle.load(Relaxed) {
                    0 => {}
                    other => T::drop(other),
                }
            }
        }
    }
    pub fn as_i64<T: AsI64>(t: T) -> i64 {
        t.as_i64()
    }
    pub trait AsI64 {
        fn as_i64(self) -> i64;
    }
    impl<'a, T: Copy + AsI64> AsI64 for &'a T {
        fn as_i64(self) -> i64 {
            (*self).as_i64()
        }
    }
    impl AsI64 for i64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    impl AsI64 for u64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    pub unsafe fn bool_lift(val: u8) -> bool {
        if cfg!(debug_assertions) {
            match val {
                0 => false,
                1 => true,
                _ => panic!("invalid bool discriminant"),
            }
        } else {
            val != 0
        }
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    pub use alloc_crate::vec::Vec;
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        unsafe {
            let layout = alloc::Layout::from_size_align_unchecked(size, align);
            alloc::dealloc(ptr, layout);
        }
    }
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}
#[rustfmt::skip]
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.47.0:symmetric:runtime@0.3.0:stream-import:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1804] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x88\x0d\x01A\x02\x01\
A\x05\x01B&\x01m\x02\x07pending\x05ready\x04\0\x0ecallback-state\x03\0\0\x04\0\x11\
callback-function\x03\x01\x04\0\x0dcallback-data\x03\x01\x04\0\x12event-subscrip\
tion\x03\x01\x04\0\x0fevent-generator\x03\x01\x04\0\x15callback-registration\x03\
\x01\x01m\x02\x07started\x0bnot-started\x04\0\x0bcall-status\x03\0\x07\x01h\x04\x01\
@\x01\x04self\x09\0\x7f\x04\0\x20[method]event-subscription.ready\x01\x0a\x01i\x04\
\x01@\x01\x0bnanosecondsw\0\x0b\x04\0'[static]event-subscription.from-timeout\x01\
\x0c\x01@\x01\x04self\x09\0\x0b\x04\0\x1e[method]event-subscription.dup\x01\x0d\x01\
@\x01\x04self\x09\x01\0\x04\0\x20[method]event-subscription.reset\x01\x0e\x01i\x05\
\x01@\0\0\x0f\x04\0\x1c[constructor]event-generator\x01\x10\x01h\x05\x01@\x01\x04\
self\x11\0\x0b\x04\0![method]event-generator.subscribe\x01\x12\x01@\x01\x04self\x11\
\x01\0\x04\0\x20[method]event-generator.activate\x01\x13\x01i\x06\x01i\x03\x01@\x01\
\x03obj\x14\0\x15\x04\0$[static]callback-registration.cancel\x01\x16\x01@\0\x01\0\
\x04\0\x03run\x01\x17\x01i\x02\x01@\x03\x07trigger\x0b\x08callback\x18\x04data\x15\
\0\x14\x04\0\x08register\x01\x19\x01@\x01\x07trigger\x0b\x01\0\x04\0\x08block-on\
\x01\x1a\x03\0*symmetric:runtime/symmetric-executor@0.3.0\x05\0\x02\x03\0\0\x12e\
vent-subscription\x01B+\x02\x03\x02\x01\x01\x04\0\x12event-subscription\x03\0\0\x04\
\0\x07address\x03\x01\x04\0\x06buffer\x03\x01\x01m\x02\x03eof\x07pending\x04\0\x0c\
stream-state\x03\0\x04\x04\0\x0astream-obj\x03\x01\x01i\x02\x01i\x03\x01@\x02\x04\
addr\x07\x08capacityw\0\x08\x04\0\x13[constructor]buffer\x01\x09\x01h\x03\x01@\x01\
\x04self\x0a\0\x07\x04\0\x1a[method]buffer.get-address\x01\x0b\x01@\x01\x04self\x0a\
\0w\x04\0\x17[method]buffer.get-size\x01\x0c\x01@\x02\x04self\x0a\x04sizew\x01\0\
\x04\0\x17[method]buffer.set-size\x01\x0d\x04\0\x17[method]buffer.capacity\x01\x0c\
\x01i\x06\x01@\0\0\x0e\x04\0\x17[constructor]stream-obj\x01\x0f\x01h\x06\x01@\x02\
\x04self\x10\x07writing\x7f\0\x0e\x04\0\x18[method]stream-obj.clone\x01\x11\x01@\
\x01\x04self\x10\0\x7f\x04\0\"[method]stream-obj.is-write-closed\x01\x12\x01j\0\x01\
\x08\x01@\x02\x04self\x10\x06buffer\x08\0\x13\x04\0\x20[method]stream-obj.start-\
reading\x01\x14\x01i\x01\x01@\x01\x04self\x10\0\x15\x04\0'[method]stream-obj.rea\
d-ready-subscribe\x01\x16\x01p\x08\x01@\x01\x04self\x10\0\x17\x04\0\x1d[method]s\
tream-obj.close-read\x01\x18\x01j\x01\x08\x01\x05\x01@\x01\x04self\x10\0\x19\x04\
\0\x1e[method]stream-obj.read-result\x01\x1a\x04\0![method]stream-obj.is-read-cl\
osed\x01\x12\x04\0\x20[method]stream-obj.start-writing\x01\x1a\x04\0([method]str\
eam-obj.write-ready-subscribe\x01\x16\x04\0![method]stream-obj.finish-writing\x01\
\x14\x03\0(symmetric:runtime/symmetric-stream@0.3.0\x05\x02\x04\0%symmetric:runt\
ime/stream-import@0.3.0\x04\0\x0b\x13\x01\0\x0dstream-import\x03\0\0\0G\x09produ\
cers\x01\x0cprocessed-by\x02\x0dwit-component\x070.240.0\x10wit-bindgen-rust\x06\
0.47.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen::rt::maybe_link_cabi_realloc();
}
