// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!

// Ensure that the *_component_type.o object is linked in
#ifdef __wasm32__
extern "C" void __component_type_object_force_link_executor_import(void);
__attribute__((used)) void
__component_type_object_force_link_executor_import_public_use_in_this_compilation_unit(
    void) {
  __component_type_object_force_link_executor_import();
}
#endif
#include "executor_import_cpp.h"
#include <cstdlib> // realloc

extern "C" void *cabi_realloc(void *ptr, size_t old_size, size_t align,
                              size_t new_size);

__attribute__((__weak__)) void *cabi_realloc(void *ptr, size_t old_size,
                                             size_t align, size_t new_size) {
  (void)old_size;
  void *ret = reinterpret_cast<void *>(align);
  if (new_size != 0) {
    ret = realloc(ptr, new_size);
    if (!ret) {
      abort();
    }
  }
  return ret;
}

extern "C" void
symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5Bresource_dropX5Dcallback_function(
    uint8_t *);
extern "C" void
symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5Bresource_dropX5Dcallback_data(
    uint8_t *);
extern "C" void
symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5Bresource_dropX5Devent_subscription(
    uint8_t *);
extern "C" int32_t
symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5BmethodX5Devent_subscriptionX2Eready(
    uint8_t *);
extern "C" uint8_t *
symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5BstaticX5Devent_subscriptionX2Efrom_timeout(
    int64_t);
extern "C" uint8_t *
symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5BmethodX5Devent_subscriptionX2Edup(
    uint8_t *);
extern "C" void
symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5BmethodX5Devent_subscriptionX2Ereset(
    uint8_t *);
extern "C" void
symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5Bresource_dropX5Devent_generator(
    uint8_t *);
extern "C" uint8_t *
symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5BconstructorX5Devent_generator();
extern "C" uint8_t *
symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5BmethodX5Devent_generatorX2Esubscribe(
    uint8_t *);
extern "C" void
symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5BmethodX5Devent_generatorX2Eactivate(
    uint8_t *);
extern "C" void
symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5Bresource_dropX5Dcallback_registration(
    uint8_t *);
extern "C" uint8_t *
symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5BstaticX5Dcallback_registrationX2Ecancel(
    uint8_t *);
extern "C" void symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00run();
extern "C" uint8_t *
symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00register(uint8_t *,
                                                                uint8_t *,
                                                                uint8_t *);
extern "C" void
symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00block_on(uint8_t *);
symmetric::runtime::symmetric_executor::CallbackFunction::~CallbackFunction() {
  if (handle != nullptr) {
    symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5Bresource_dropX5Dcallback_function(
        handle);
  }
}
symmetric::runtime::symmetric_executor::CallbackFunction::CallbackFunction(
    wit::ResourceImportBase &&b)
    : wit::ResourceImportBase(std::move(b)) {}
symmetric::runtime::symmetric_executor::CallbackData::~CallbackData() {
  if (handle != nullptr) {
    symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5Bresource_dropX5Dcallback_data(
        handle);
  }
}
symmetric::runtime::symmetric_executor::CallbackData::CallbackData(
    wit::ResourceImportBase &&b)
    : wit::ResourceImportBase(std::move(b)) {}
symmetric::runtime::symmetric_executor::EventSubscription::
    ~EventSubscription() {
  if (handle != nullptr) {
    symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5Bresource_dropX5Devent_subscription(
        handle);
  }
}
bool symmetric::runtime::symmetric_executor::EventSubscription::Ready() const {
  auto ret =
      symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5BmethodX5Devent_subscriptionX2Eready(
          (*this).get_handle());
  return static_cast<bool>(ret);
}
symmetric::runtime::symmetric_executor::EventSubscription
symmetric::runtime::symmetric_executor::EventSubscription::FromTimeout(
    uint64_t nanoseconds) {
  auto ret =
      symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5BstaticX5Devent_subscriptionX2Efrom_timeout(
          static_cast<int64_t>(nanoseconds));
  return wit::ResourceImportBase{ret};
}
symmetric::runtime::symmetric_executor::EventSubscription
symmetric::runtime::symmetric_executor::EventSubscription::Dup() const {
  auto ret =
      symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5BmethodX5Devent_subscriptionX2Edup(
          (*this).get_handle());
  return wit::ResourceImportBase{ret};
}
void symmetric::runtime::symmetric_executor::EventSubscription::Reset() const {
  symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5BmethodX5Devent_subscriptionX2Ereset(
      (*this).get_handle());
}
symmetric::runtime::symmetric_executor::EventSubscription::EventSubscription(
    wit::ResourceImportBase &&b)
    : wit::ResourceImportBase(std::move(b)) {}
symmetric::runtime::symmetric_executor::EventGenerator::~EventGenerator() {
  if (handle != nullptr) {
    symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5Bresource_dropX5Devent_generator(
        handle);
  }
}
symmetric::runtime::symmetric_executor::EventGenerator::EventGenerator() {
  auto ret =
      symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5BconstructorX5Devent_generator();
  this->handle = wit::ResourceImportBase{ret}.into_handle();
}
symmetric::runtime::symmetric_executor::EventSubscription
symmetric::runtime::symmetric_executor::EventGenerator::Subscribe() const {
  auto ret =
      symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5BmethodX5Devent_generatorX2Esubscribe(
          (*this).get_handle());
  return wit::ResourceImportBase{ret};
}
void symmetric::runtime::symmetric_executor::EventGenerator::Activate() const {
  symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5BmethodX5Devent_generatorX2Eactivate(
      (*this).get_handle());
}
symmetric::runtime::symmetric_executor::EventGenerator::EventGenerator(
    wit::ResourceImportBase &&b)
    : wit::ResourceImportBase(std::move(b)) {}
symmetric::runtime::symmetric_executor::CallbackRegistration::
    ~CallbackRegistration() {
  if (handle != nullptr) {
    symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5Bresource_dropX5Dcallback_registration(
        handle);
  }
}
symmetric::runtime::symmetric_executor::CallbackData
symmetric::runtime::symmetric_executor::CallbackRegistration::Cancel(
    symmetric_executor::CallbackRegistration &&obj) {
  auto ret =
      symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00X5BstaticX5Dcallback_registrationX2Ecancel(
          obj.into_handle());
  return wit::ResourceImportBase{ret};
}
symmetric::runtime::symmetric_executor::CallbackRegistration::
    CallbackRegistration(wit::ResourceImportBase &&b)
    : wit::ResourceImportBase(std::move(b)) {}
void symmetric::runtime::symmetric_executor::Run() {
  symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00run();
}
symmetric::runtime::symmetric_executor::CallbackRegistration
symmetric::runtime::symmetric_executor::Register(EventSubscription &&trigger,
                                                 CallbackFunction &&callback,
                                                 CallbackData &&data) {
  auto ret = symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00register(
      trigger.into_handle(), callback.into_handle(), data.into_handle());
  return wit::ResourceImportBase{ret};
}
void symmetric::runtime::symmetric_executor::BlockOn(
    EventSubscription &&trigger) {
  symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E0X00block_on(
      trigger.into_handle());
}

// Component Adapters
