// Generated by `wit-bindgen` 0.54.0. DO NOT EDIT!
#ifndef __CPP_GUEST_BINDINGS_MODULE_H
#define __CPP_GUEST_BINDINGS_MODULE_H
#define WIT_SYMMETRIC
#include "executor_import_cpp.h"
#include "wit.h"
#include <cassert>
#include <cstdint>
#include <expected>
#include <optional>
#include <utility>
namespace symmetric {
namespace runtime {
namespace symmetric_stream {
class Address;
class Buffer;
class StreamObj;
using EventSubscription = symmetric_executor::EventSubscription;
class Address : public wit::ResourceImportBase {

public:
  ~Address();
  Address(wit::ResourceImportBase &&);
  Address(Address &&) = default;
  Address &operator=(Address &&) = default;
  Address(const Address &) = delete;
  Address &operator=(const Address &) = delete;
};

class Buffer : public wit::ResourceImportBase {

public:
  ~Buffer();
  Buffer(symmetric_stream::Address &&addr, uint64_t capacity);
  Address GetAddress() const;
  uint64_t GetSize() const;
  void SetSize(uint64_t size) const;
  uint64_t Capacity() const;
  Buffer(wit::ResourceImportBase &&);
  Buffer(Buffer &&) = default;
  Buffer &operator=(Buffer &&) = default;
  Buffer(const Buffer &) = delete;
  Buffer &operator=(const Buffer &) = delete;
};

enum class StreamState : uint8_t {
  kEof = 0,
  kPending = 1,
};

class StreamObj : public wit::ResourceImportBase {

public:
  ~StreamObj();
  StreamObj();
  StreamObj Clone(bool writing) const;
  bool IsWriteClosed() const;
  std::expected<void, Buffer>
  StartReading(symmetric_stream::Buffer &&buffer) const;
  symmetric_executor::EventSubscription ReadReadySubscribe() const;
  wit::vector<Buffer> CloseRead() const;
  std::expected<Buffer, StreamState> ReadResult() const;
  bool IsReadClosed() const;
  std::expected<Buffer, StreamState> StartWriting() const;
  symmetric_executor::EventSubscription WriteReadySubscribe() const;
  std::expected<void, Buffer>
  FinishWriting(symmetric_stream::Buffer &&buffer) const;
  StreamObj(wit::ResourceImportBase &&);
  StreamObj(StreamObj &&) = default;
  StreamObj &operator=(StreamObj &&) = default;
  StreamObj(const StreamObj &) = delete;
  StreamObj &operator=(const StreamObj &) = delete;
};

} // namespace symmetric_stream
} // namespace runtime
} // namespace symmetric

#endif
