[package]
name = "wit-bindgen-bridge"
authors = ["Christof Petig <christof.petig@arcor.de>"]
version = { workspace = true }
edition = { workspace = true }
repository = 'https://github.com/cpetig/wit-bindgen'
license = { workspace = true }
rust-version = { workspace = true }
description = """
Bridge binding (forwarding) generator for WIT and the component model, targeting w2c2 and wamr.
"""

[lib]
doctest = false
test = false

[dependencies]
wit-bindgen-core = { workspace = true }
wit-component = { workspace = true }
anyhow = { workspace = true }
heck = { workspace = true }
clap = { workspace = true, optional = true }

#[dev-dependencies]
#test-helpers = { path = '../test-helpers' }
