// Generated by `wit-bindgen` 0.54.0. DO NOT EDIT!
// Options used:
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod symmetric {
    pub mod runtime {
        /// This interface will only work with symmetric ABI (shared everything),
        /// it can't be composed with the canonical ABI
        /// Asynchronous executor functionality for symmetric ABI
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod symmetric_executor {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            /// These pseudo-resources are just used to
            /// pass pointers to register
            /// Return value of an event callback
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum CallbackState {
                /// Call the function again
                Pending,
                /// The function has completed, all results are written, data is freed,
                /// calling the function again is not permitted as data became invalid!
                Ready,
            }
            impl ::core::fmt::Debug for CallbackState {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        CallbackState::Pending => {
                            f.debug_tuple("CallbackState::Pending").finish()
                        }
                        CallbackState::Ready => {
                            f.debug_tuple("CallbackState::Ready").finish()
                        }
                    }
                }
            }
            impl CallbackState {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> CallbackState {
                    if !cfg!(debug_assertions) {
                        return unsafe { ::core::mem::transmute(val) };
                    }
                    match val {
                        0 => CallbackState::Pending,
                        1 => CallbackState::Ready,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            /// This wraps a user provided function of type
            /// `fn (callback-data) -> callback-state`
            #[derive(Debug)]
            #[repr(transparent)]
            pub struct CallbackFunction {
                handle: _rt::Resource<CallbackFunction>,
            }
            impl CallbackFunction {
                #[doc(hidden)]
                pub unsafe fn from_handle(handle: usize) -> Self {
                    Self {
                        handle: unsafe { _rt::Resource::from_handle(handle) },
                    }
                }
                #[doc(hidden)]
                pub fn take_handle(&self) -> usize {
                    _rt::Resource::take_handle(&self.handle)
                }
                #[doc(hidden)]
                pub fn handle(&self) -> usize {
                    _rt::Resource::handle(&self.handle)
                }
            }
            unsafe impl _rt::WasmResource for CallbackFunction {
                #[inline]
                unsafe fn drop(_handle: usize) {
                    #[link(
                        wasm_import_module = "symmetric:runtime/symmetric-executor@0.3.1"
                    )]
                    unsafe extern "C" {
                        #[allow(non_snake_case)]
                        #[cfg_attr(
                            target_arch = "wasm32",
                            link_name = "[resource-drop]callback-function"
                        )]
                        fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E1X00X5Bresource_dropX5Dcallback_function(
                            _: *mut u8,
                        );
                    }
                    unsafe {
                        symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E1X00X5Bresource_dropX5Dcallback_function(
                            _handle as *mut u8,
                        )
                    };
                }
            }
            /// This wraps opaque user data, freed by the callback when
            /// it returns ready
            #[derive(Debug)]
            #[repr(transparent)]
            pub struct CallbackData {
                handle: _rt::Resource<CallbackData>,
            }
            impl CallbackData {
                #[doc(hidden)]
                pub unsafe fn from_handle(handle: usize) -> Self {
                    Self {
                        handle: unsafe { _rt::Resource::from_handle(handle) },
                    }
                }
                #[doc(hidden)]
                pub fn take_handle(&self) -> usize {
                    _rt::Resource::take_handle(&self.handle)
                }
                #[doc(hidden)]
                pub fn handle(&self) -> usize {
                    _rt::Resource::handle(&self.handle)
                }
            }
            unsafe impl _rt::WasmResource for CallbackData {
                #[inline]
                unsafe fn drop(_handle: usize) {
                    #[link(
                        wasm_import_module = "symmetric:runtime/symmetric-executor@0.3.1"
                    )]
                    unsafe extern "C" {
                        #[allow(non_snake_case)]
                        #[cfg_attr(
                            target_arch = "wasm32",
                            link_name = "[resource-drop]callback-data"
                        )]
                        fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E1X00X5Bresource_dropX5Dcallback_data(
                            _: *mut u8,
                        );
                    }
                    unsafe {
                        symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E1X00X5Bresource_dropX5Dcallback_data(
                            _handle as *mut u8,
                        )
                    };
                }
            }
            /// The receiving side of an event
            #[derive(Debug)]
            #[repr(transparent)]
            pub struct EventSubscription {
                handle: _rt::Resource<EventSubscription>,
            }
            impl EventSubscription {
                #[doc(hidden)]
                pub unsafe fn from_handle(handle: usize) -> Self {
                    Self {
                        handle: unsafe { _rt::Resource::from_handle(handle) },
                    }
                }
                #[doc(hidden)]
                pub fn take_handle(&self) -> usize {
                    _rt::Resource::take_handle(&self.handle)
                }
                #[doc(hidden)]
                pub fn handle(&self) -> usize {
                    _rt::Resource::handle(&self.handle)
                }
            }
            unsafe impl _rt::WasmResource for EventSubscription {
                #[inline]
                unsafe fn drop(_handle: usize) {
                    #[link(
                        wasm_import_module = "symmetric:runtime/symmetric-executor@0.3.1"
                    )]
                    unsafe extern "C" {
                        #[allow(non_snake_case)]
                        #[cfg_attr(
                            target_arch = "wasm32",
                            link_name = "[resource-drop]event-subscription"
                        )]
                        fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E1X00X5Bresource_dropX5Devent_subscription(
                            _: *mut u8,
                        );
                    }
                    unsafe {
                        symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E1X00X5Bresource_dropX5Devent_subscription(
                            _handle as *mut u8,
                        )
                    };
                }
            }
            /// A user controlled event
            #[derive(Debug)]
            #[repr(transparent)]
            pub struct EventGenerator {
                handle: _rt::Resource<EventGenerator>,
            }
            impl EventGenerator {
                #[doc(hidden)]
                pub unsafe fn from_handle(handle: usize) -> Self {
                    Self {
                        handle: unsafe { _rt::Resource::from_handle(handle) },
                    }
                }
                #[doc(hidden)]
                pub fn take_handle(&self) -> usize {
                    _rt::Resource::take_handle(&self.handle)
                }
                #[doc(hidden)]
                pub fn handle(&self) -> usize {
                    _rt::Resource::handle(&self.handle)
                }
            }
            unsafe impl _rt::WasmResource for EventGenerator {
                #[inline]
                unsafe fn drop(_handle: usize) {
                    #[link(
                        wasm_import_module = "symmetric:runtime/symmetric-executor@0.3.1"
                    )]
                    unsafe extern "C" {
                        #[allow(non_snake_case)]
                        #[cfg_attr(
                            target_arch = "wasm32",
                            link_name = "[resource-drop]event-generator"
                        )]
                        fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E1X00X5Bresource_dropX5Devent_generator(
                            _: *mut u8,
                        );
                    }
                    unsafe {
                        symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E1X00X5Bresource_dropX5Devent_generator(
                            _handle as *mut u8,
                        )
                    };
                }
            }
            /// Handle to cancel a callback registration
            #[derive(Debug)]
            #[repr(transparent)]
            pub struct CallbackRegistration {
                handle: _rt::Resource<CallbackRegistration>,
            }
            impl CallbackRegistration {
                #[doc(hidden)]
                pub unsafe fn from_handle(handle: usize) -> Self {
                    Self {
                        handle: unsafe { _rt::Resource::from_handle(handle) },
                    }
                }
                #[doc(hidden)]
                pub fn take_handle(&self) -> usize {
                    _rt::Resource::take_handle(&self.handle)
                }
                #[doc(hidden)]
                pub fn handle(&self) -> usize {
                    _rt::Resource::handle(&self.handle)
                }
            }
            unsafe impl _rt::WasmResource for CallbackRegistration {
                #[inline]
                unsafe fn drop(_handle: usize) {
                    #[link(
                        wasm_import_module = "symmetric:runtime/symmetric-executor@0.3.1"
                    )]
                    unsafe extern "C" {
                        #[allow(non_snake_case)]
                        #[cfg_attr(
                            target_arch = "wasm32",
                            link_name = "[resource-drop]callback-registration"
                        )]
                        fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E1X00X5Bresource_dropX5Dcallback_registration(
                            _: *mut u8,
                        );
                    }
                    unsafe {
                        symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E1X00X5Bresource_dropX5Dcallback_registration(
                            _handle as *mut u8,
                        )
                    };
                }
            }
            /// Return value of an async call, lowest bit encoding
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum CallStatus {
                /// For symmetric this means that processing has started, parameters should still remain valid until null,
                /// params-read = non-null, results-written,done = null
                Started,
                /// For symmetric: Retry the call (temporarily out of memory)
                NotStarted,
            }
            impl ::core::fmt::Debug for CallStatus {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        CallStatus::Started => {
                            f.debug_tuple("CallStatus::Started").finish()
                        }
                        CallStatus::NotStarted => {
                            f.debug_tuple("CallStatus::NotStarted").finish()
                        }
                    }
                }
            }
            impl CallStatus {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> CallStatus {
                    if !cfg!(debug_assertions) {
                        return unsafe { ::core::mem::transmute(val) };
                    }
                    match val {
                        0 => CallStatus::Started,
                        1 => CallStatus::NotStarted,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            impl EventSubscription {
                #[allow(unused_unsafe, clippy::all)]
                /// Whether the event is active (used by poll implementation)
                #[allow(async_fn_in_trait)]
                pub fn ready(&self) -> bool {
                    unsafe {
                        #[link(
                            wasm_import_module = "symmetric:runtime/symmetric-executor@0.3.1"
                        )]
                        unsafe extern "C" {
                            #[allow(non_snake_case)]
                            #[cfg_attr(
                                target_arch = "wasm32",
                                link_name = "[method]event-subscription.ready"
                            )]
                            fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E1X00X5BmethodX5Devent_subscriptionX2Eready(
                                _: *mut u8,
                            ) -> i32;
                        }
                        let ret = symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E1X00X5BmethodX5Devent_subscriptionX2Eready(
                            (self).handle() as *mut u8,
                        );
                        _rt::bool_lift(ret as u8)
                    }
                }
            }
            impl EventSubscription {
                #[allow(unused_unsafe, clippy::all)]
                /// Create a timeout event
                #[allow(async_fn_in_trait)]
                pub fn from_timeout(nanoseconds: u64) -> EventSubscription {
                    unsafe {
                        #[link(
                            wasm_import_module = "symmetric:runtime/symmetric-executor@0.3.1"
                        )]
                        unsafe extern "C" {
                            #[allow(non_snake_case)]
                            #[cfg_attr(
                                target_arch = "wasm32",
                                link_name = "[static]event-subscription.from-timeout"
                            )]
                            fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E1X00X5BstaticX5Devent_subscriptionX2Efrom_timeout(
                                _: i64,
                            ) -> *mut u8;
                        }
                        let ret = symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E1X00X5BstaticX5Devent_subscriptionX2Efrom_timeout(
                            _rt::as_i64(&nanoseconds),
                        );
                        EventSubscription::from_handle(ret as usize)
                    }
                }
            }
            impl EventSubscription {
                #[allow(unused_unsafe, clippy::all)]
                /// Duplicate the subscription (e.g. for repeated callback registering, same cost as subscribe)
                #[allow(async_fn_in_trait)]
                pub fn dup(&self) -> EventSubscription {
                    unsafe {
                        #[link(
                            wasm_import_module = "symmetric:runtime/symmetric-executor@0.3.1"
                        )]
                        unsafe extern "C" {
                            #[allow(non_snake_case)]
                            #[cfg_attr(
                                target_arch = "wasm32",
                                link_name = "[method]event-subscription.dup"
                            )]
                            fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E1X00X5BmethodX5Devent_subscriptionX2Edup(
                                _: *mut u8,
                            ) -> *mut u8;
                        }
                        let ret = symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E1X00X5BmethodX5Devent_subscriptionX2Edup(
                            (self).handle() as *mut u8,
                        );
                        EventSubscription::from_handle(ret as usize)
                    }
                }
            }
            impl EventSubscription {
                #[allow(unused_unsafe, clippy::all)]
                /// Reset subscription to be inactive, only next trigger will ready it
                #[allow(async_fn_in_trait)]
                pub fn reset(&self) -> () {
                    unsafe {
                        #[link(
                            wasm_import_module = "symmetric:runtime/symmetric-executor@0.3.1"
                        )]
                        unsafe extern "C" {
                            #[allow(non_snake_case)]
                            #[cfg_attr(
                                target_arch = "wasm32",
                                link_name = "[method]event-subscription.reset"
                            )]
                            fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E1X00X5BmethodX5Devent_subscriptionX2Ereset(
                                _: *mut u8,
                            );
                        }
                        symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E1X00X5BmethodX5Devent_subscriptionX2Ereset(
                            (self).handle() as *mut u8,
                        );
                    }
                }
            }
            impl EventGenerator {
                #[allow(unused_unsafe, clippy::all)]
                #[allow(async_fn_in_trait)]
                pub fn new() -> Self {
                    unsafe {
                        #[link(
                            wasm_import_module = "symmetric:runtime/symmetric-executor@0.3.1"
                        )]
                        unsafe extern "C" {
                            #[allow(non_snake_case)]
                            #[cfg_attr(
                                target_arch = "wasm32",
                                link_name = "[constructor]event-generator"
                            )]
                            fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E1X00X5BconstructorX5Devent_generator() -> *mut u8;
                        }
                        let ret = symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E1X00X5BconstructorX5Devent_generator();
                        EventGenerator::from_handle(ret as usize)
                    }
                }
            }
            impl EventGenerator {
                #[allow(unused_unsafe, clippy::all)]
                /// Get the receiving side (to pass to other parts of the program)
                /// Make sure to reset if you only need future events
                #[allow(async_fn_in_trait)]
                pub fn subscribe(&self) -> EventSubscription {
                    unsafe {
                        #[link(
                            wasm_import_module = "symmetric:runtime/symmetric-executor@0.3.1"
                        )]
                        unsafe extern "C" {
                            #[allow(non_snake_case)]
                            #[cfg_attr(
                                target_arch = "wasm32",
                                link_name = "[method]event-generator.subscribe"
                            )]
                            fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E1X00X5BmethodX5Devent_generatorX2Esubscribe(
                                _: *mut u8,
                            ) -> *mut u8;
                        }
                        let ret = symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E1X00X5BmethodX5Devent_generatorX2Esubscribe(
                            (self).handle() as *mut u8,
                        );
                        EventSubscription::from_handle(ret as usize)
                    }
                }
            }
            impl EventGenerator {
                #[allow(unused_unsafe, clippy::all)]
                /// Trigger all subscribers
                #[allow(async_fn_in_trait)]
                pub fn activate(&self) -> () {
                    unsafe {
                        #[link(
                            wasm_import_module = "symmetric:runtime/symmetric-executor@0.3.1"
                        )]
                        unsafe extern "C" {
                            #[allow(non_snake_case)]
                            #[cfg_attr(
                                target_arch = "wasm32",
                                link_name = "[method]event-generator.activate"
                            )]
                            fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E1X00X5BmethodX5Devent_generatorX2Eactivate(
                                _: *mut u8,
                            );
                        }
                        symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E1X00X5BmethodX5Devent_generatorX2Eactivate(
                            (self).handle() as *mut u8,
                        );
                    }
                }
            }
            impl CallbackRegistration {
                #[allow(unused_unsafe, clippy::all)]
                /// returns the data passed to the registration
                #[allow(async_fn_in_trait)]
                pub fn cancel(obj: CallbackRegistration) -> CallbackData {
                    unsafe {
                        #[link(
                            wasm_import_module = "symmetric:runtime/symmetric-executor@0.3.1"
                        )]
                        unsafe extern "C" {
                            #[allow(non_snake_case)]
                            #[cfg_attr(
                                target_arch = "wasm32",
                                link_name = "[static]callback-registration.cancel"
                            )]
                            fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E1X00X5BstaticX5Dcallback_registrationX2Ecancel(
                                _: *mut u8,
                            ) -> *mut u8;
                        }
                        let ret = symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E1X00X5BstaticX5Dcallback_registrationX2Ecancel(
                            (&obj).take_handle() as *mut u8,
                        );
                        CallbackData::from_handle(ret as usize)
                    }
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Wait until all registered events have completed
            #[allow(async_fn_in_trait)]
            pub fn run() -> () {
                unsafe {
                    #[link(
                        wasm_import_module = "symmetric:runtime/symmetric-executor@0.3.1"
                    )]
                    unsafe extern "C" {
                        #[allow(non_snake_case)]
                        #[cfg_attr(target_arch = "wasm32", link_name = "run")]
                        fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E1X00run();
                    }
                    symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E1X00run();
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Register a callback for an event
            #[allow(async_fn_in_trait)]
            pub fn register(
                trigger: EventSubscription,
                callback: CallbackFunction,
                data: CallbackData,
            ) -> CallbackRegistration {
                unsafe {
                    #[link(
                        wasm_import_module = "symmetric:runtime/symmetric-executor@0.3.1"
                    )]
                    unsafe extern "C" {
                        #[allow(non_snake_case)]
                        #[cfg_attr(target_arch = "wasm32", link_name = "register")]
                        fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E1X00register(
                            _: *mut u8,
                            _: *mut u8,
                            _: *mut u8,
                        ) -> *mut u8;
                    }
                    let ret = symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E1X00register(
                        (&trigger).take_handle() as *mut u8,
                        (&callback).take_handle() as *mut u8,
                        (&data).take_handle() as *mut u8,
                    );
                    CallbackRegistration::from_handle(ret as usize)
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Register a callback for an event, skip if already active
            #[allow(async_fn_in_trait)]
            pub fn register_unique(
                trigger: EventSubscription,
                callback: CallbackFunction,
                data: CallbackData,
            ) -> Option<CallbackRegistration> {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 2 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 2
                            * ::core::mem::size_of::<*const u8>()],
                    );
                    let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[link(
                        wasm_import_module = "symmetric:runtime/symmetric-executor@0.3.1"
                    )]
                    unsafe extern "C" {
                        #[allow(non_snake_case)]
                        #[cfg_attr(
                            target_arch = "wasm32",
                            link_name = "register-unique"
                        )]
                        fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E1X00register_unique(
                            _: *mut u8,
                            _: *mut u8,
                            _: *mut u8,
                            _: *mut u8,
                        );
                    }
                    symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E1X00register_unique(
                        (&trigger).take_handle() as *mut u8,
                        (&callback).take_handle() as *mut u8,
                        (&data).take_handle() as *mut u8,
                        ptr0,
                    );
                    let l1 = i32::from(*ptr0.add(0).cast::<u8>());
                    match l1 {
                        0 => None,
                        1 => {
                            let e = {
                                let l2 = *ptr0
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                CallbackRegistration::from_handle(l2 as usize)
                            };
                            Some(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    }
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Wait for a specific event
            #[allow(async_fn_in_trait)]
            pub fn block_on(trigger: EventSubscription) -> () {
                unsafe {
                    #[link(
                        wasm_import_module = "symmetric:runtime/symmetric-executor@0.3.1"
                    )]
                    unsafe extern "C" {
                        #[allow(non_snake_case)]
                        #[cfg_attr(target_arch = "wasm32", link_name = "block-on")]
                        fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E1X00block_on(
                            _: *mut u8,
                        );
                    }
                    symmetricX3AruntimeX2Fsymmetric_executorX400X2E3X2E1X00block_on(
                        (&trigger).take_handle() as *mut u8,
                    );
                }
            }
        }
    }
}
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod symmetric {
        pub mod runtime {
            /// language neutral stream implementation
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod symmetric_stream {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type EventSubscription = super::super::super::super::symmetric::runtime::symmetric_executor::EventSubscription;
                #[derive(Debug)]
                #[repr(transparent)]
                pub struct Address {
                    handle: _rt::Resource<Address>,
                }
                type _AddressRep<T> = Option<T>;
                impl Address {
                    /// Creates a new resource from the specified representation.
                    ///
                    /// This function will create a new resource handle by moving `val` onto
                    /// the heap and then passing that heap pointer to the component model to
                    /// create a handle. The owned handle is then returned as `Address`.
                    pub fn new<T: GuestAddress>(val: T) -> Self {
                        Self::type_guard::<T>();
                        let val: _AddressRep<T> = Some(val);
                        let ptr: *mut _AddressRep<T> = _rt::Box::into_raw(
                            _rt::Box::new(val),
                        );
                        unsafe { Self::from_handle(T::_resource_new(ptr.cast())) }
                    }
                    /// Gets access to the underlying `T` which represents this resource.
                    pub fn get<T: GuestAddress>(&self) -> &T {
                        let ptr = unsafe { &*self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }
                    /// Gets mutable access to the underlying `T` which represents this
                    /// resource.
                    pub fn get_mut<T: GuestAddress>(&mut self) -> &mut T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_mut().unwrap()
                    }
                    /// Consumes this resource and returns the underlying `T`.
                    pub fn into_inner<T: GuestAddress>(self) -> T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.take().unwrap()
                    }
                    #[doc(hidden)]
                    pub unsafe fn from_handle(handle: usize) -> Self {
                        Self {
                            handle: unsafe { _rt::Resource::from_handle(handle) },
                        }
                    }
                    #[doc(hidden)]
                    pub fn take_handle(&self) -> usize {
                        _rt::Resource::take_handle(&self.handle)
                    }
                    #[doc(hidden)]
                    pub fn handle(&self) -> usize {
                        _rt::Resource::handle(&self.handle)
                    }
                    #[doc(hidden)]
                    fn type_guard<T: 'static>() {
                        use core::any::TypeId;
                        static mut LAST_TYPE: Option<TypeId> = None;
                        unsafe {
                            assert!(! cfg!(target_feature = "atomics"));
                            let id = TypeId::of::<T>();
                            match LAST_TYPE {
                                Some(ty) => {
                                    assert!(
                                        ty == id, "cannot use two types with this resource type"
                                    )
                                }
                                None => LAST_TYPE = Some(id),
                            }
                        }
                    }
                    #[doc(hidden)]
                    pub unsafe fn dtor<T: 'static>(handle: *mut u8) {
                        Self::type_guard::<T>();
                        let _ = unsafe {
                            _rt::Box::from_raw(handle as *mut _AddressRep<T>)
                        };
                    }
                    fn as_ptr<T: GuestAddress>(&self) -> *mut _AddressRep<T> {
                        Address::type_guard::<T>();
                        T::_resource_rep(self.handle()).cast()
                    }
                }
                /// A borrowed version of [`Address`] which represents a borrowed value
                /// with the lifetime `'a`.
                #[derive(Debug)]
                #[repr(transparent)]
                pub struct AddressBorrow<'a> {
                    rep: *mut u8,
                    _marker: core::marker::PhantomData<&'a Address>,
                }
                impl<'a> AddressBorrow<'a> {
                    #[doc(hidden)]
                    pub unsafe fn lift(rep: usize) -> Self {
                        Self {
                            rep: rep as *mut u8,
                            _marker: core::marker::PhantomData,
                        }
                    }
                    /// Gets access to the underlying `T` in this resource.
                    pub fn get<T: GuestAddress>(&self) -> &'a T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }
                    fn as_ptr<T: 'static>(&self) -> *mut _AddressRep<T> {
                        Address::type_guard::<T>();
                        self.rep.cast()
                    }
                }
                unsafe impl _rt::WasmResource for Address {
                    #[inline]
                    unsafe fn drop(_handle: usize) {
                        #[link(
                            wasm_import_module = "symmetric:runtime/symmetric-stream@0.3.1"
                        )]
                        unsafe extern "C" {
                            #[allow(non_snake_case)]
                            #[cfg_attr(
                                target_arch = "wasm32",
                                link_name = "[resource-drop]address"
                            )]
                            fn symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E1X00X5Bresource_dropX5Daddress(
                                _: *mut u8,
                            );
                        }
                        unsafe {
                            symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E1X00X5Bresource_dropX5Daddress(
                                _handle as *mut u8,
                            )
                        };
                    }
                }
                /// special zero allocation/copy data type (caller provided buffer)
                #[derive(Debug)]
                #[repr(transparent)]
                pub struct Buffer {
                    handle: _rt::Resource<Buffer>,
                }
                type _BufferRep<T> = Option<T>;
                impl Buffer {
                    /// Creates a new resource from the specified representation.
                    ///
                    /// This function will create a new resource handle by moving `val` onto
                    /// the heap and then passing that heap pointer to the component model to
                    /// create a handle. The owned handle is then returned as `Buffer`.
                    pub fn new<T: GuestBuffer>(val: T) -> Self {
                        Self::type_guard::<T>();
                        let val: _BufferRep<T> = Some(val);
                        let ptr: *mut _BufferRep<T> = _rt::Box::into_raw(
                            _rt::Box::new(val),
                        );
                        unsafe { Self::from_handle(T::_resource_new(ptr.cast())) }
                    }
                    /// Gets access to the underlying `T` which represents this resource.
                    pub fn get<T: GuestBuffer>(&self) -> &T {
                        let ptr = unsafe { &*self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }
                    /// Gets mutable access to the underlying `T` which represents this
                    /// resource.
                    pub fn get_mut<T: GuestBuffer>(&mut self) -> &mut T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_mut().unwrap()
                    }
                    /// Consumes this resource and returns the underlying `T`.
                    pub fn into_inner<T: GuestBuffer>(self) -> T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.take().unwrap()
                    }
                    #[doc(hidden)]
                    pub unsafe fn from_handle(handle: usize) -> Self {
                        Self {
                            handle: unsafe { _rt::Resource::from_handle(handle) },
                        }
                    }
                    #[doc(hidden)]
                    pub fn take_handle(&self) -> usize {
                        _rt::Resource::take_handle(&self.handle)
                    }
                    #[doc(hidden)]
                    pub fn handle(&self) -> usize {
                        _rt::Resource::handle(&self.handle)
                    }
                    #[doc(hidden)]
                    fn type_guard<T: 'static>() {
                        use core::any::TypeId;
                        static mut LAST_TYPE: Option<TypeId> = None;
                        unsafe {
                            assert!(! cfg!(target_feature = "atomics"));
                            let id = TypeId::of::<T>();
                            match LAST_TYPE {
                                Some(ty) => {
                                    assert!(
                                        ty == id, "cannot use two types with this resource type"
                                    )
                                }
                                None => LAST_TYPE = Some(id),
                            }
                        }
                    }
                    #[doc(hidden)]
                    pub unsafe fn dtor<T: 'static>(handle: *mut u8) {
                        Self::type_guard::<T>();
                        let _ = unsafe {
                            _rt::Box::from_raw(handle as *mut _BufferRep<T>)
                        };
                    }
                    fn as_ptr<T: GuestBuffer>(&self) -> *mut _BufferRep<T> {
                        Buffer::type_guard::<T>();
                        T::_resource_rep(self.handle()).cast()
                    }
                }
                /// A borrowed version of [`Buffer`] which represents a borrowed value
                /// with the lifetime `'a`.
                #[derive(Debug)]
                #[repr(transparent)]
                pub struct BufferBorrow<'a> {
                    rep: *mut u8,
                    _marker: core::marker::PhantomData<&'a Buffer>,
                }
                impl<'a> BufferBorrow<'a> {
                    #[doc(hidden)]
                    pub unsafe fn lift(rep: usize) -> Self {
                        Self {
                            rep: rep as *mut u8,
                            _marker: core::marker::PhantomData,
                        }
                    }
                    /// Gets access to the underlying `T` in this resource.
                    pub fn get<T: GuestBuffer>(&self) -> &'a T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }
                    fn as_ptr<T: 'static>(&self) -> *mut _BufferRep<T> {
                        Buffer::type_guard::<T>();
                        self.rep.cast()
                    }
                }
                unsafe impl _rt::WasmResource for Buffer {
                    #[inline]
                    unsafe fn drop(_handle: usize) {
                        #[link(
                            wasm_import_module = "symmetric:runtime/symmetric-stream@0.3.1"
                        )]
                        unsafe extern "C" {
                            #[allow(non_snake_case)]
                            #[cfg_attr(
                                target_arch = "wasm32",
                                link_name = "[resource-drop]buffer"
                            )]
                            fn symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E1X00X5Bresource_dropX5Dbuffer(
                                _: *mut u8,
                            );
                        }
                        unsafe {
                            symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E1X00X5Bresource_dropX5Dbuffer(
                                _handle as *mut u8,
                            )
                        };
                    }
                }
                #[repr(u8)]
                #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
                pub enum StreamState {
                    Eof,
                    Pending,
                }
                impl StreamState {
                    pub fn name(&self) -> &'static str {
                        match self {
                            StreamState::Eof => "eof",
                            StreamState::Pending => "pending",
                        }
                    }
                    pub fn message(&self) -> &'static str {
                        match self {
                            StreamState::Eof => "",
                            StreamState::Pending => "",
                        }
                    }
                }
                impl ::core::fmt::Debug for StreamState {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("StreamState")
                            .field("code", &(*self as i32))
                            .field("name", &self.name())
                            .field("message", &self.message())
                            .finish()
                    }
                }
                impl ::core::fmt::Display for StreamState {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        write!(f, "{} (error {})", self.name(), * self as i32)
                    }
                }
                impl ::core::error::Error for StreamState {}
                impl StreamState {
                    #[doc(hidden)]
                    pub unsafe fn _lift(val: u8) -> StreamState {
                        if !cfg!(debug_assertions) {
                            return unsafe { ::core::mem::transmute(val) };
                        }
                        match val {
                            0 => StreamState::Eof,
                            1 => StreamState::Pending,
                            _ => panic!("invalid enum discriminant"),
                        }
                    }
                }
                #[derive(Debug)]
                #[repr(transparent)]
                pub struct StreamObj {
                    handle: _rt::Resource<StreamObj>,
                }
                type _StreamObjRep<T> = Option<T>;
                impl StreamObj {
                    /// Creates a new resource from the specified representation.
                    ///
                    /// This function will create a new resource handle by moving `val` onto
                    /// the heap and then passing that heap pointer to the component model to
                    /// create a handle. The owned handle is then returned as `StreamObj`.
                    pub fn new<T: GuestStreamObj>(val: T) -> Self {
                        Self::type_guard::<T>();
                        let val: _StreamObjRep<T> = Some(val);
                        let ptr: *mut _StreamObjRep<T> = _rt::Box::into_raw(
                            _rt::Box::new(val),
                        );
                        unsafe { Self::from_handle(T::_resource_new(ptr.cast())) }
                    }
                    /// Gets access to the underlying `T` which represents this resource.
                    pub fn get<T: GuestStreamObj>(&self) -> &T {
                        let ptr = unsafe { &*self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }
                    /// Gets mutable access to the underlying `T` which represents this
                    /// resource.
                    pub fn get_mut<T: GuestStreamObj>(&mut self) -> &mut T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_mut().unwrap()
                    }
                    /// Consumes this resource and returns the underlying `T`.
                    pub fn into_inner<T: GuestStreamObj>(self) -> T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.take().unwrap()
                    }
                    #[doc(hidden)]
                    pub unsafe fn from_handle(handle: usize) -> Self {
                        Self {
                            handle: unsafe { _rt::Resource::from_handle(handle) },
                        }
                    }
                    #[doc(hidden)]
                    pub fn take_handle(&self) -> usize {
                        _rt::Resource::take_handle(&self.handle)
                    }
                    #[doc(hidden)]
                    pub fn handle(&self) -> usize {
                        _rt::Resource::handle(&self.handle)
                    }
                    #[doc(hidden)]
                    fn type_guard<T: 'static>() {
                        use core::any::TypeId;
                        static mut LAST_TYPE: Option<TypeId> = None;
                        unsafe {
                            assert!(! cfg!(target_feature = "atomics"));
                            let id = TypeId::of::<T>();
                            match LAST_TYPE {
                                Some(ty) => {
                                    assert!(
                                        ty == id, "cannot use two types with this resource type"
                                    )
                                }
                                None => LAST_TYPE = Some(id),
                            }
                        }
                    }
                    #[doc(hidden)]
                    pub unsafe fn dtor<T: 'static>(handle: *mut u8) {
                        Self::type_guard::<T>();
                        let _ = unsafe {
                            _rt::Box::from_raw(handle as *mut _StreamObjRep<T>)
                        };
                    }
                    fn as_ptr<T: GuestStreamObj>(&self) -> *mut _StreamObjRep<T> {
                        StreamObj::type_guard::<T>();
                        T::_resource_rep(self.handle()).cast()
                    }
                }
                /// A borrowed version of [`StreamObj`] which represents a borrowed value
                /// with the lifetime `'a`.
                #[derive(Debug)]
                #[repr(transparent)]
                pub struct StreamObjBorrow<'a> {
                    rep: *mut u8,
                    _marker: core::marker::PhantomData<&'a StreamObj>,
                }
                impl<'a> StreamObjBorrow<'a> {
                    #[doc(hidden)]
                    pub unsafe fn lift(rep: usize) -> Self {
                        Self {
                            rep: rep as *mut u8,
                            _marker: core::marker::PhantomData,
                        }
                    }
                    /// Gets access to the underlying `T` in this resource.
                    pub fn get<T: GuestStreamObj>(&self) -> &'a T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }
                    fn as_ptr<T: 'static>(&self) -> *mut _StreamObjRep<T> {
                        StreamObj::type_guard::<T>();
                        self.rep.cast()
                    }
                }
                unsafe impl _rt::WasmResource for StreamObj {
                    #[inline]
                    unsafe fn drop(_handle: usize) {
                        #[link(
                            wasm_import_module = "symmetric:runtime/symmetric-stream@0.3.1"
                        )]
                        unsafe extern "C" {
                            #[allow(non_snake_case)]
                            #[cfg_attr(
                                target_arch = "wasm32",
                                link_name = "[resource-drop]stream-obj"
                            )]
                            fn symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E1X00X5Bresource_dropX5Dstream_obj(
                                _: *mut u8,
                            );
                        }
                        unsafe {
                            symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E1X00X5Bresource_dropX5Dstream_obj(
                                _handle as *mut u8,
                            )
                        };
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_constructor_buffer_cabi<T_: GuestBuffer>(
                    arg0: *mut u8,
                    arg1: i64,
                ) -> *mut u8 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                        let result0 = {
                            Buffer::new(
                                T_::new(Address::from_handle(arg0 as usize), arg1 as u64),
                            )
                        };
                        (result0).take_handle() as *mut u8
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_method_buffer_get_address_cabi<T_: GuestBuffer>(
                    arg0: *mut u8,
                ) -> *mut u8 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                        let result0 = {
                            T_::get_address(BufferBorrow::lift(arg0 as usize).get())
                        };
                        (result0).take_handle() as *mut u8
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_method_buffer_get_size_cabi<T_: GuestBuffer>(
                    arg0: *mut u8,
                ) -> i64 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                        let result0 = {
                            T_::get_size(BufferBorrow::lift(arg0 as usize).get())
                        };
                        _rt::as_i64(result0)
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_method_buffer_set_size_cabi<T_: GuestBuffer>(
                    arg0: *mut u8,
                    arg1: i64,
                ) {
                    unsafe {
                        #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                        {
                            T_::set_size(
                                BufferBorrow::lift(arg0 as usize).get(),
                                arg1 as u64,
                            )
                        };
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_method_buffer_capacity_cabi<T_: GuestBuffer>(
                    arg0: *mut u8,
                ) -> i64 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                        let result0 = {
                            T_::capacity(BufferBorrow::lift(arg0 as usize).get())
                        };
                        _rt::as_i64(result0)
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_constructor_stream_obj_cabi<T_: GuestStreamObj>() -> *mut u8 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                        let result0 = { StreamObj::new(T_::new()) };
                        (result0).take_handle() as *mut u8
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_method_stream_obj_clone_cabi<T_: GuestStreamObj>(
                    arg0: *mut u8,
                    arg1: i32,
                ) -> *mut u8 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                        let result0 = {
                            T_::clone(
                                StreamObjBorrow::lift(arg0 as usize).get(),
                                _rt::bool_lift(arg1 as u8),
                            )
                        };
                        (result0).take_handle() as *mut u8
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_method_stream_obj_is_write_closed_cabi<
                    T_: GuestStreamObj,
                >(arg0: *mut u8) -> i32 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                        let result0 = {
                            T_::is_write_closed(
                                StreamObjBorrow::lift(arg0 as usize).get(),
                            )
                        };
                        match result0 {
                            true => 1,
                            false => 0,
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_method_stream_obj_start_reading_cabi<
                    T_: GuestStreamObj,
                >(arg0: *mut u8, arg1: *mut u8, arg2: *mut u8) {
                    unsafe {
                        #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                        let result0 = {
                            T_::start_reading(
                                StreamObjBorrow::lift(arg0 as usize).get(),
                                Buffer::from_handle(arg1 as usize),
                            )
                        };
                        match result0 {
                            Ok(_) => {
                                *arg2.add(0).cast::<u8>() = (0i32) as u8;
                            }
                            Err(e) => {
                                *arg2.add(0).cast::<u8>() = (1i32) as u8;
                                *arg2
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>() = (e).take_handle() as *mut u8;
                            }
                        };
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_method_stream_obj_read_ready_subscribe_cabi<
                    T_: GuestStreamObj,
                >(arg0: *mut u8) -> *mut u8 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                        let result0 = {
                            T_::read_ready_subscribe(
                                StreamObjBorrow::lift(arg0 as usize).get(),
                            )
                        };
                        (result0).take_handle() as *mut u8
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_method_stream_obj_close_read_cabi<
                    T_: GuestStreamObj,
                >(arg0: *mut u8, arg1: *mut u8) {
                    unsafe {
                        #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                        let result0 = {
                            T_::close_read(StreamObjBorrow::lift(arg0 as usize).get())
                        };
                        let vec1 = result0;
                        let len1 = vec1.len();
                        let layout1 = _rt::alloc::Layout::from_size_align(
                                vec1.len() * ::core::mem::size_of::<*const u8>(),
                                ::core::mem::size_of::<*const u8>(),
                            )
                            .unwrap();
                        let (result1, _cleanup1) = wit_bindgen::rt::Cleanup::new(
                            layout1,
                        );
                        if let Some(cleanup) = _cleanup1 {
                            cleanup.forget();
                        }
                        for (i, e) in vec1.into_iter().enumerate() {
                            let base = result1
                                .add(i * ::core::mem::size_of::<*const u8>());
                            {
                                *base.add(0).cast::<*mut u8>() = (e).take_handle()
                                    as *mut u8;
                            }
                        }
                        *arg1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len1;
                        *arg1.add(0).cast::<*mut u8>() = result1;
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_method_stream_obj_read_result_cabi<
                    T_: GuestStreamObj,
                >(arg0: *mut u8, arg1: *mut u8) {
                    unsafe {
                        #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                        let result0 = {
                            T_::read_result(StreamObjBorrow::lift(arg0 as usize).get())
                        };
                        match result0 {
                            Ok(e) => {
                                *arg1.add(0).cast::<u8>() = (0i32) as u8;
                                *arg1
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>() = (e).take_handle() as *mut u8;
                            }
                            Err(e) => {
                                *arg1.add(0).cast::<u8>() = (1i32) as u8;
                                *arg1
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<u8>() = (e.clone() as i32) as u8;
                            }
                        };
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_method_stream_obj_is_read_closed_cabi<
                    T_: GuestStreamObj,
                >(arg0: *mut u8) -> i32 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                        let result0 = {
                            T_::is_read_closed(
                                StreamObjBorrow::lift(arg0 as usize).get(),
                            )
                        };
                        match result0 {
                            true => 1,
                            false => 0,
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_method_stream_obj_start_writing_cabi<
                    T_: GuestStreamObj,
                >(arg0: *mut u8, arg1: *mut u8) {
                    unsafe {
                        #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                        let result0 = {
                            T_::start_writing(StreamObjBorrow::lift(arg0 as usize).get())
                        };
                        match result0 {
                            Ok(e) => {
                                *arg1.add(0).cast::<u8>() = (0i32) as u8;
                                *arg1
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>() = (e).take_handle() as *mut u8;
                            }
                            Err(e) => {
                                *arg1.add(0).cast::<u8>() = (1i32) as u8;
                                *arg1
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<u8>() = (e.clone() as i32) as u8;
                            }
                        };
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_method_stream_obj_write_ready_subscribe_cabi<
                    T_: GuestStreamObj,
                >(arg0: *mut u8) -> *mut u8 {
                    unsafe {
                        #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                        let result0 = {
                            T_::write_ready_subscribe(
                                StreamObjBorrow::lift(arg0 as usize).get(),
                            )
                        };
                        (result0).take_handle() as *mut u8
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case, unused_unsafe)]
                pub unsafe fn _export_method_stream_obj_finish_writing_cabi<
                    T_: GuestStreamObj,
                >(arg0: *mut u8, arg1: *mut u8, arg2: *mut u8) {
                    unsafe {
                        #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                        let result0 = {
                            T_::finish_writing(
                                StreamObjBorrow::lift(arg0 as usize).get(),
                                Buffer::from_handle(arg1 as usize),
                            )
                        };
                        match result0 {
                            Ok(_) => {
                                *arg2.add(0).cast::<u8>() = (0i32) as u8;
                            }
                            Err(e) => {
                                *arg2.add(0).cast::<u8>() = (1i32) as u8;
                                *arg2
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>() = (e).take_handle() as *mut u8;
                            }
                        };
                    }
                }
                pub trait Guest {
                    type Address: GuestAddress;
                    type Buffer: GuestBuffer;
                    type StreamObj: GuestStreamObj;
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_drop_address_cabi<T: GuestAddress>(arg0: usize) {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    Address::dtor::<T>(arg0 as *mut u8);
                }
                pub trait GuestAddress: 'static {
                    #[doc(hidden)]
                    unsafe fn _resource_new(val: *mut u8) -> usize
                    where
                        Self: Sized,
                    {
                        val as usize
                    }
                    #[doc(hidden)]
                    fn _resource_rep(handle: usize) -> *mut u8
                    where
                        Self: Sized,
                    {
                        handle as *mut u8
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_drop_buffer_cabi<T: GuestBuffer>(arg0: usize) {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    Buffer::dtor::<T>(arg0 as *mut u8);
                }
                pub trait GuestBuffer: 'static {
                    #[doc(hidden)]
                    unsafe fn _resource_new(val: *mut u8) -> usize
                    where
                        Self: Sized,
                    {
                        val as usize
                    }
                    #[doc(hidden)]
                    fn _resource_rep(handle: usize) -> *mut u8
                    where
                        Self: Sized,
                    {
                        handle as *mut u8
                    }
                    #[allow(async_fn_in_trait)]
                    fn new(addr: Address, capacity: u64) -> Self;
                    #[allow(async_fn_in_trait)]
                    fn get_address(&self) -> Address;
                    #[allow(async_fn_in_trait)]
                    fn get_size(&self) -> u64;
                    #[allow(async_fn_in_trait)]
                    fn set_size(&self, size: u64) -> ();
                    #[allow(async_fn_in_trait)]
                    fn capacity(&self) -> u64;
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_drop_streamObj_cabi<T: GuestStreamObj>(
                    arg0: usize,
                ) {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    StreamObj::dtor::<T>(arg0 as *mut u8);
                }
                pub trait GuestStreamObj: 'static {
                    #[doc(hidden)]
                    unsafe fn _resource_new(val: *mut u8) -> usize
                    where
                        Self: Sized,
                    {
                        val as usize
                    }
                    #[doc(hidden)]
                    fn _resource_rep(handle: usize) -> *mut u8
                    where
                        Self: Sized,
                    {
                        handle as *mut u8
                    }
                    #[allow(async_fn_in_trait)]
                    fn new() -> Self;
                    /// create a new instance e.g. for reading or tasks
                    /// (Assumption: This is never used to duplicate the writing side)
                    #[allow(async_fn_in_trait)]
                    fn clone(&self, writing: bool) -> StreamObj;
                    /// reading (in roughly chronological order)
                    /// indicates EOF
                    #[allow(async_fn_in_trait)]
                    fn is_write_closed(&self) -> bool;
                    #[allow(async_fn_in_trait)]
                    fn start_reading(&self, buffer: Buffer) -> Result<(), Buffer>;
                    #[allow(async_fn_in_trait)]
                    fn read_ready_subscribe(&self) -> EventSubscription;
                    /// close the reading side, returning any in-flight buffer(s)
                    #[allow(async_fn_in_trait)]
                    fn close_read(&self) -> _rt::Vec<Buffer>;
                    #[allow(async_fn_in_trait)]
                    fn read_result(&self) -> Result<Buffer, StreamState>;
                    /// writing
                    #[allow(async_fn_in_trait)]
                    fn is_read_closed(&self) -> bool;
                    #[allow(async_fn_in_trait)]
                    fn start_writing(&self) -> Result<Buffer, StreamState>;
                    #[allow(async_fn_in_trait)]
                    fn write_ready_subscribe(&self) -> EventSubscription;
                    #[allow(async_fn_in_trait)]
                    fn finish_writing(&self, buffer: Buffer) -> Result<(), Buffer>;
                }
                #[doc(hidden)]
                macro_rules! __export_symmetric_runtime_symmetric_stream_0_3_1_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[cfg_attr(target_arch = "wasm32", unsafe
                        (export_name = "[constructor]buffer"))]
                        #[cfg_attr(not(target_arch = "wasm32"), no_mangle)]
                        #[allow(non_snake_case)] unsafe extern "C" fn
                        symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E1X00X5BconstructorX5Dbuffer(arg0
                        : * mut u8, arg1 : i64,) -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_constructor_buffer_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::Buffer > (arg0, arg1) } }
                        #[cfg_attr(target_arch = "wasm32", unsafe (export_name =
                        "[method]buffer.get-address"))] #[cfg_attr(not(target_arch =
                        "wasm32"), no_mangle)] #[allow(non_snake_case)] unsafe extern "C"
                        fn
                        symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E1X00X5BmethodX5DbufferX2Eget_address(arg0
                        : * mut u8,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_method_buffer_get_address_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::Buffer > (arg0) } }
                        #[cfg_attr(target_arch = "wasm32", unsafe (export_name =
                        "[method]buffer.get-size"))] #[cfg_attr(not(target_arch =
                        "wasm32"), no_mangle)] #[allow(non_snake_case)] unsafe extern "C"
                        fn
                        symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E1X00X5BmethodX5DbufferX2Eget_size(arg0
                        : * mut u8,) -> i64 { unsafe { $($path_to_types)*::
                        _export_method_buffer_get_size_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::Buffer > (arg0) } }
                        #[cfg_attr(target_arch = "wasm32", unsafe (export_name =
                        "[method]buffer.set-size"))] #[cfg_attr(not(target_arch =
                        "wasm32"), no_mangle)] #[allow(non_snake_case)] unsafe extern "C"
                        fn
                        symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E1X00X5BmethodX5DbufferX2Eset_size(arg0
                        : * mut u8, arg1 : i64,) { unsafe { $($path_to_types)*::
                        _export_method_buffer_set_size_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::Buffer > (arg0, arg1) } }
                        #[cfg_attr(target_arch = "wasm32", unsafe (export_name =
                        "[method]buffer.capacity"))] #[cfg_attr(not(target_arch =
                        "wasm32"), no_mangle)] #[allow(non_snake_case)] unsafe extern "C"
                        fn
                        symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E1X00X5BmethodX5DbufferX2Ecapacity(arg0
                        : * mut u8,) -> i64 { unsafe { $($path_to_types)*::
                        _export_method_buffer_capacity_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::Buffer > (arg0) } }
                        #[cfg_attr(target_arch = "wasm32", unsafe (export_name =
                        "[constructor]stream-obj"))] #[cfg_attr(not(target_arch =
                        "wasm32"), no_mangle)] #[allow(non_snake_case)] unsafe extern "C"
                        fn
                        symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E1X00X5BconstructorX5Dstream_obj()
                        -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_constructor_stream_obj_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::StreamObj > () } }
                        #[cfg_attr(target_arch = "wasm32", unsafe (export_name =
                        "[method]stream-obj.clone"))] #[cfg_attr(not(target_arch =
                        "wasm32"), no_mangle)] #[allow(non_snake_case)] unsafe extern "C"
                        fn
                        symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E1X00X5BmethodX5Dstream_objX2Eclone(arg0
                        : * mut u8, arg1 : i32,) -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_method_stream_obj_clone_cabi::<<$ty
                        as $($path_to_types)*:: Guest >::StreamObj > (arg0, arg1) } }
                        #[cfg_attr(target_arch = "wasm32", unsafe (export_name =
                        "[method]stream-obj.is-write-closed"))]
                        #[cfg_attr(not(target_arch = "wasm32"), no_mangle)]
                        #[allow(non_snake_case)] unsafe extern "C" fn
                        symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E1X00X5BmethodX5Dstream_objX2Eis_write_closed(arg0
                        : * mut u8,) -> i32 { unsafe { $($path_to_types)*::
                        _export_method_stream_obj_is_write_closed_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::StreamObj > (arg0) } }
                        #[cfg_attr(target_arch = "wasm32", unsafe (export_name =
                        "[method]stream-obj.start-reading"))] #[cfg_attr(not(target_arch
                        = "wasm32"), no_mangle)] #[allow(non_snake_case)] unsafe extern
                        "C" fn
                        symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E1X00X5BmethodX5Dstream_objX2Estart_reading(arg0
                        : * mut u8, arg1 : * mut u8, arg2 : * mut u8,) { unsafe {
                        $($path_to_types)*::
                        _export_method_stream_obj_start_reading_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::StreamObj > (arg0, arg1, arg2) } }
                        #[cfg_attr(target_arch = "wasm32", unsafe (export_name =
                        "[method]stream-obj.read-ready-subscribe"))]
                        #[cfg_attr(not(target_arch = "wasm32"), no_mangle)]
                        #[allow(non_snake_case)] unsafe extern "C" fn
                        symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E1X00X5BmethodX5Dstream_objX2Eread_ready_subscribe(arg0
                        : * mut u8,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_method_stream_obj_read_ready_subscribe_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::StreamObj > (arg0) } }
                        #[cfg_attr(target_arch = "wasm32", unsafe (export_name =
                        "[method]stream-obj.close-read"))] #[cfg_attr(not(target_arch =
                        "wasm32"), no_mangle)] #[allow(non_snake_case)] unsafe extern "C"
                        fn
                        symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E1X00X5BmethodX5Dstream_objX2Eclose_read(arg0
                        : * mut u8, arg1 : * mut u8,) { unsafe { $($path_to_types)*::
                        _export_method_stream_obj_close_read_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::StreamObj > (arg0, arg1) } }
                        #[cfg_attr(target_arch = "wasm32", unsafe (export_name =
                        "[method]stream-obj.read-result"))] #[cfg_attr(not(target_arch =
                        "wasm32"), no_mangle)] #[allow(non_snake_case)] unsafe extern "C"
                        fn
                        symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E1X00X5BmethodX5Dstream_objX2Eread_result(arg0
                        : * mut u8, arg1 : * mut u8,) { unsafe { $($path_to_types)*::
                        _export_method_stream_obj_read_result_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::StreamObj > (arg0, arg1) } }
                        #[cfg_attr(target_arch = "wasm32", unsafe (export_name =
                        "[method]stream-obj.is-read-closed"))] #[cfg_attr(not(target_arch
                        = "wasm32"), no_mangle)] #[allow(non_snake_case)] unsafe extern
                        "C" fn
                        symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E1X00X5BmethodX5Dstream_objX2Eis_read_closed(arg0
                        : * mut u8,) -> i32 { unsafe { $($path_to_types)*::
                        _export_method_stream_obj_is_read_closed_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::StreamObj > (arg0) } }
                        #[cfg_attr(target_arch = "wasm32", unsafe (export_name =
                        "[method]stream-obj.start-writing"))] #[cfg_attr(not(target_arch
                        = "wasm32"), no_mangle)] #[allow(non_snake_case)] unsafe extern
                        "C" fn
                        symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E1X00X5BmethodX5Dstream_objX2Estart_writing(arg0
                        : * mut u8, arg1 : * mut u8,) { unsafe { $($path_to_types)*::
                        _export_method_stream_obj_start_writing_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::StreamObj > (arg0, arg1) } }
                        #[cfg_attr(target_arch = "wasm32", unsafe (export_name =
                        "[method]stream-obj.write-ready-subscribe"))]
                        #[cfg_attr(not(target_arch = "wasm32"), no_mangle)]
                        #[allow(non_snake_case)] unsafe extern "C" fn
                        symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E1X00X5BmethodX5Dstream_objX2Ewrite_ready_subscribe(arg0
                        : * mut u8,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_method_stream_obj_write_ready_subscribe_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::StreamObj > (arg0) } }
                        #[cfg_attr(target_arch = "wasm32", unsafe (export_name =
                        "[method]stream-obj.finish-writing"))] #[cfg_attr(not(target_arch
                        = "wasm32"), no_mangle)] #[allow(non_snake_case)] unsafe extern
                        "C" fn
                        symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E1X00X5BmethodX5Dstream_objX2Efinish_writing(arg0
                        : * mut u8, arg1 : * mut u8, arg2 : * mut u8,) { unsafe {
                        $($path_to_types)*::
                        _export_method_stream_obj_finish_writing_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::StreamObj > (arg0, arg1, arg2) } }
                        #[cfg_attr(not(target_arch = "wasm32"), no_mangle)]
                        #[allow(non_snake_case)] unsafe extern "C" fn
                        symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E1X00X5Bresource_dropX5Daddress(arg0
                        : usize) { $($path_to_types)*:: _export_drop_address_cabi::<<$ty
                        as $($path_to_types)*:: Guest >::Address > (arg0) }
                        #[cfg_attr(not(target_arch = "wasm32"), no_mangle)]
                        #[allow(non_snake_case)] unsafe extern "C" fn
                        symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E1X00X5Bresource_dropX5Dbuffer(arg0
                        : usize) { $($path_to_types)*:: _export_drop_buffer_cabi::<<$ty
                        as $($path_to_types)*:: Guest >::Buffer > (arg0) }
                        #[cfg_attr(not(target_arch = "wasm32"), no_mangle)]
                        #[allow(non_snake_case)] unsafe extern "C" fn
                        symmetricX3AruntimeX2Fsymmetric_streamX400X2E3X2E1X00X5Bresource_dropX5Dstream_obj(arg0
                        : usize) { $($path_to_types)*::
                        _export_drop_streamObj_cabi::<<$ty as $($path_to_types)*:: Guest
                        >::StreamObj > (arg0) } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_symmetric_runtime_symmetric_stream_0_3_1_cabi;
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, unused_imports, clippy::all)]
    use core::fmt;
    use core::marker;
    use core::sync::atomic::{AtomicUsize, Ordering::Relaxed};
    /// A type which represents a component model resource, either imported or
    /// exported into this component.
    ///
    /// This is a low-level wrapper which handles the lifetime of the resource
    /// (namely this has a destructor). The `T` provided defines the component model
    /// intrinsics that this wrapper uses.
    ///
    /// One of the chief purposes of this type is to provide `Deref` implementations
    /// to access the underlying data when it is owned.
    ///
    /// This type is primarily used in generated code for exported and imported
    /// resources.
    #[repr(transparent)]
    pub struct Resource<T: WasmResource> {
        handle: AtomicUsize,
        _marker: marker::PhantomData<T>,
    }
    /// A trait which all wasm resources implement, namely providing the ability to
    /// drop a resource.
    ///
    /// This generally is implemented by generated code, not user-facing code.
    #[allow(clippy::missing_safety_doc)]
    pub unsafe trait WasmResource {
        /// Invokes the `[resource-drop]...` intrinsic.
        unsafe fn drop(handle: usize);
    }
    impl<T: WasmResource> Resource<T> {
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: usize) -> Self {
            debug_assert!(handle != 0 && handle != 0);
            Self {
                handle: AtomicUsize::new(handle),
                _marker: marker::PhantomData,
            }
        }
        /// Takes ownership of the handle owned by `resource`.
        ///
        /// Note that this ideally would be `into_handle` taking `Resource<T>` by
        /// ownership. The code generator does not enable that in all situations,
        /// unfortunately, so this is provided instead.
        ///
        /// Also note that `take_handle` is in theory only ever called on values
        /// owned by a generated function. For example a generated function might
        /// take `Resource<T>` as an argument but then call `take_handle` on a
        /// reference to that argument. In that sense the dynamic nature of
        /// `take_handle` should only be exposed internally to generated code, not
        /// to user code.
        #[doc(hidden)]
        pub fn take_handle(resource: &Resource<T>) -> usize {
            resource.handle.swap(0, Relaxed)
        }
        #[doc(hidden)]
        pub fn handle(resource: &Resource<T>) -> usize {
            resource.handle.load(Relaxed)
        }
    }
    impl<T: WasmResource> fmt::Debug for Resource<T> {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            f.debug_struct("Resource").field("handle", &self.handle).finish()
        }
    }
    impl<T: WasmResource> Drop for Resource<T> {
        fn drop(&mut self) {
            unsafe {
                match self.handle.load(Relaxed) {
                    0 => {}
                    other => T::drop(other),
                }
            }
        }
    }
    pub unsafe fn bool_lift(val: u8) -> bool {
        if cfg!(debug_assertions) {
            match val {
                0 => false,
                1 => true,
                _ => panic!("invalid bool discriminant"),
            }
        } else {
            val != 0
        }
    }
    pub fn as_i64<T: AsI64>(t: T) -> i64 {
        t.as_i64()
    }
    pub trait AsI64 {
        fn as_i64(self) -> i64;
    }
    impl<'a, T: Copy + AsI64> AsI64 for &'a T {
        fn as_i64(self) -> i64 {
            (*self).as_i64()
        }
    }
    impl AsI64 for i64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    impl AsI64 for u64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    pub use alloc_crate::boxed::Box;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen::rt::run_ctors_once();
    }
    pub use alloc_crate::alloc;
    pub use alloc_crate::vec::Vec;
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_stream_impl_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::symmetric::runtime::symmetric_stream::__export_symmetric_runtime_symmetric_stream_0_3_1_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::symmetric::runtime::symmetric_stream);
    };
}
#[doc(inline)]
pub(crate) use __export_stream_impl_impl as export;
#[rustfmt::skip]
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.54.0:symmetric:runtime@0.3.1:stream-impl:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1853] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xbb\x0d\x01A\x02\x01\
A\x05\x01B)\x01m\x02\x07pending\x05ready\x04\0\x0ecallback-state\x03\0\0\x04\0\x11\
callback-function\x03\x01\x04\0\x0dcallback-data\x03\x01\x04\0\x12event-subscrip\
tion\x03\x01\x04\0\x0fevent-generator\x03\x01\x04\0\x15callback-registration\x03\
\x01\x01m\x02\x07started\x0bnot-started\x04\0\x0bcall-status\x03\0\x07\x01h\x04\x01\
@\x01\x04self\x09\0\x7f\x04\0\x20[method]event-subscription.ready\x01\x0a\x01i\x04\
\x01@\x01\x0bnanosecondsw\0\x0b\x04\0'[static]event-subscription.from-timeout\x01\
\x0c\x01@\x01\x04self\x09\0\x0b\x04\0\x1e[method]event-subscription.dup\x01\x0d\x01\
@\x01\x04self\x09\x01\0\x04\0\x20[method]event-subscription.reset\x01\x0e\x01i\x05\
\x01@\0\0\x0f\x04\0\x1c[constructor]event-generator\x01\x10\x01h\x05\x01@\x01\x04\
self\x11\0\x0b\x04\0![method]event-generator.subscribe\x01\x12\x01@\x01\x04self\x11\
\x01\0\x04\0\x20[method]event-generator.activate\x01\x13\x01i\x06\x01i\x03\x01@\x01\
\x03obj\x14\0\x15\x04\0$[static]callback-registration.cancel\x01\x16\x01@\0\x01\0\
\x04\0\x03run\x01\x17\x01i\x02\x01@\x03\x07trigger\x0b\x08callback\x18\x04data\x15\
\0\x14\x04\0\x08register\x01\x19\x01k\x14\x01@\x03\x07trigger\x0b\x08callback\x18\
\x04data\x15\0\x1a\x04\0\x0fregister-unique\x01\x1b\x01@\x01\x07trigger\x0b\x01\0\
\x04\0\x08block-on\x01\x1c\x03\0*symmetric:runtime/symmetric-executor@0.3.1\x05\0\
\x02\x03\0\0\x12event-subscription\x01B+\x02\x03\x02\x01\x01\x04\0\x12event-subs\
cription\x03\0\0\x04\0\x07address\x03\x01\x04\0\x06buffer\x03\x01\x01m\x02\x03eo\
f\x07pending\x04\0\x0cstream-state\x03\0\x04\x04\0\x0astream-obj\x03\x01\x01i\x02\
\x01i\x03\x01@\x02\x04addr\x07\x08capacityw\0\x08\x04\0\x13[constructor]buffer\x01\
\x09\x01h\x03\x01@\x01\x04self\x0a\0\x07\x04\0\x1a[method]buffer.get-address\x01\
\x0b\x01@\x01\x04self\x0a\0w\x04\0\x17[method]buffer.get-size\x01\x0c\x01@\x02\x04\
self\x0a\x04sizew\x01\0\x04\0\x17[method]buffer.set-size\x01\x0d\x04\0\x17[metho\
d]buffer.capacity\x01\x0c\x01i\x06\x01@\0\0\x0e\x04\0\x17[constructor]stream-obj\
\x01\x0f\x01h\x06\x01@\x02\x04self\x10\x07writing\x7f\0\x0e\x04\0\x18[method]str\
eam-obj.clone\x01\x11\x01@\x01\x04self\x10\0\x7f\x04\0\"[method]stream-obj.is-wr\
ite-closed\x01\x12\x01j\0\x01\x08\x01@\x02\x04self\x10\x06buffer\x08\0\x13\x04\0\
\x20[method]stream-obj.start-reading\x01\x14\x01i\x01\x01@\x01\x04self\x10\0\x15\
\x04\0'[method]stream-obj.read-ready-subscribe\x01\x16\x01p\x08\x01@\x01\x04self\
\x10\0\x17\x04\0\x1d[method]stream-obj.close-read\x01\x18\x01j\x01\x08\x01\x05\x01\
@\x01\x04self\x10\0\x19\x04\0\x1e[method]stream-obj.read-result\x01\x1a\x04\0![m\
ethod]stream-obj.is-read-closed\x01\x12\x04\0\x20[method]stream-obj.start-writin\
g\x01\x1a\x04\0([method]stream-obj.write-ready-subscribe\x01\x16\x04\0![method]s\
tream-obj.finish-writing\x01\x14\x04\0(symmetric:runtime/symmetric-stream@0.3.1\x05\
\x02\x04\0#symmetric:runtime/stream-impl@0.3.1\x04\0\x0b\x11\x01\0\x0bstream-imp\
l\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.245.1\x10\
wit-bindgen-rust\x060.54.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen::rt::maybe_link_cabi_realloc();
}
