
all:
	make -C cpp/component_b $@
	make -C cpp/mesh $@
	make -C cpp/component_a $@

bindgen:
	make -C cpp/component_b $@
	make -C cpp/mesh $@
	make -C cpp/component_a $@

clean:
	make -C cpp/component_b $@
	make -C cpp/mesh $@
	make -C cpp/component_a $@
	